### ISSUE TITLE
Provide a better sync between master and stable branches

### ISSUE THREAD

**Issue by brianredbeard** [vmware/open-vm-tools#10]
Currently tracking this repository is nearly impossible.  When a single commit is "2 commits ahead of master" yet has "Showing  1,046 changed files  with 186,655 additions and 982 deletions." This does lead to a good view into what is happening with the project.  Additionally it doesn't even allow for use of the auditing of the codebase when errors like "Sorry, we could not display the entire diff because too many files (1,046) changed." are thrown.

Affects #8

**Comment by oliverkurth** [comment]
Thanks Brian for that input.

github is not our primary repository for VMware tools development. So for every new release, we push to github in one huge chunk. However, we do provide a ChangeLog file that has separate entries for all changes related to tools. This isn't as good as a complete git log, but at least provides insight into the changes.

**Comment by ml8mr** [comment]
I take it the primary repository is not public? That does make things a bit challenging... I don't suppose the current model is changing any time soon?

The real pain of the ChangeLog file is that there is no way to match a comment to a specific commit - or even get in the right ballpark for the related code. Not to mention the ability to bisect; cherry-pick patches; etc...

**Comment by bzed** [comment]
Having all changes in one big commit is completely useless. You could even remove your stuff from github instead of suggesting that you are doing open-source-software properly.

Problems like quiesce fs hanging a VM could be easily bisected and fixed if there would be a history of commits. You'd have a pull request to get it fixed already, I'm sure.

In the current state its just a shame for vmware, nothing else. Not even really useful.

**Comment by ravindravmw** [comment]
We appreciate your concern bzed.

There is a difference between releasing in open source and developing as open source project. We are not yet developing open-vm-tools as open source project. We develop this code internally and release as proprietary and in open source form.

We might get to develop open-vm-tools as open source project in future, but not in near term because it would need significant code redesign and process change on our end which needs to be justified.

Coming back to your concern, could you please elaborate on quiesce FS hanging a VM issue and we will be able to help with what change you are after?

**Comment by bzed** [comment]
@ravindravmw I appreciate that you are trying to open tour development process. At the moment, for me - as the open-vm-tools maintainer for Debian - its hard to impossible to figure out when and where a bug was introduced, which makes maintaining a package something between hard and impossible.

The quiesce issue is described in #7 and http://bugs.debian.org/784398 - with the last release IO is being frozen when quiescing FSs and then the VM is basically dead as IO never comes back...
vmbackup shows
  vmsvc[6299]: [ warning] [vmbackup] Failed to send event to the VMX: Guest is not privileged enough to invoke RPC.

but the same issue also happens if you just take a snapshot manually.

Discussing that issue in #7 is the better idea, lets talk about open-source software here :)

**Comment by brianredbeard** [comment]
@bzed I agree 1000%.  As someone involved with CoreOS there are similar challenges with auditing/patching. If we needed to carry a patch between it being submitted and merged it would make for an extremely painful experience.

**Comment by stanguturi** [comment]
> Currently tracking this repository is nearly impossible. When a single commit is "2 commits ahead of master" yet has "Showing 1,046 changed files with 186,655 additions and 982 deletions."

> Having all changes in one big commit is completely useless.

Many things have changed since this issue was opened. We now have various branches in the OVT repository. devel branch is being updated regularly. Also, there are other stable-x.y.z branches. Please check them out for the detailed information for each commit/change. It's no longer a single bit commit.

Thanks.
