### ISSUE TITLE
CentOS 7.2 - time is not synchronised with host

### ISSUE THREAD

**Issue by zdm** [vmware/open-vm-tools#118]
I have clean minimal CeontOS installed as guest in vmware workstation 12.5.
Then installed open vm tools from the sources, using following commands:
```
wget --no-verbose -O - https://github.com/vmware/open-vm-tools/files/576680/open-vm-tools-10.1.0-4449150.tar.gz | tar -C /usr/src/open-vm-tools --strip-components=3 -xzf -

./configure --without-pam --without-xerces --without-x --without-icu
make -j$(nproc)
make install
```

Timesync between host and guest is enabled.
When I power on or wake up guest from suspend - time is not syncing.

For Debian guest timesync works with open vm tools normally.
Also, if I installed vmware tools from vmware workstation distribution - timesync works as expected for both CentoOS and Debian.

**Comment by jhgit** [comment]
timesync works for me on a CentOS 7.2 guest.

open-vm-tools-9.10.2-5.el7_2.x86_64

**Comment by jhgit** [comment]
I should have added it is working for me is in an ESX server environment (6.something - I don't administer the ESX server).

**Comment by zdm** [comment]
Also, it has started working for me, after i installed open vm tools
from the centos repository.

**Comment by jhgit** [comment]
FWIW, the centos rpm is built with:

===============
%configure \
    --without-kernel-modules \
    --disable-static \
    --enable-deploypkg \
    --without-xmlsecurity
sed -i -e 's! -shared ! -Wl,--as-needed\0!g' libtool
================

I don't know if the different configure flags are important for the problem you're describing (although I guess I'd be surprised).  But you could try building from source again with those flags to see if you can still reproduce your problem.  If not, clarify the issue here (or close the bug if appropriate).  If so, try to identify the difference between the sources you are using and the sources from the centos package (yumdownloader --source open-vm-tools).

**Comment by zdm** [comment]
Currently everything works with ovt from CentOS yum repository.
