### ISSUE TITLE
the status of vmware tools is running(not installed)

### ISSUE THREAD

**Issue by seamaner** [vmware/open-vm-tools#131]
I have port open-vm-tools to my linux OS, and the vmtoolsd is running.
But why the status of vmware tools is "running(not installed)" in the vSphere Client ?

**Comment by oliverkurth** [comment]
Did you try restarting vmtoolsd? It's possible that you uninstalled VMware Tools after starting the vmtoolsd from open-vm-tools.

Otherwise please send vmware.log from the ESXi, and tools logs with debugging enabled. These files might contain sensitive information, so please don't post them here - you can send them to my email address: okurth@vmware.com.

You can enable debugging in /etc/vmware/tools.conf with:

`[logging]
log = true
 
# Enable tools service logging to a file.
vmtoolsd.level = debug
vmtoolsd.handler = file
vmtoolsd.data = /var/log/vmtoolsd.log
 
# Enable 'vmsvc' service logging to a file.
vmsvc.level = debug
vmsvc.handler = file
vmsvc.data = /var/log/vmsvc.log
 `

Also, what Linux OS are you using? Did you build open-vm-tools yourself, and how? What version of ESXi?

**Comment by seamaner** [comment]
I have sent the email to you.

**Comment by stanguturi** [comment]
Can you power off the VM and restart it? Check if the problem still exists.

**Comment by stanguturi** [comment]
I work with Oliver and got the log file that you have sent. It seems, you don't have HGFSserver plugin in the VM? Is there any specific reason why that plugin was removed / not installed. Please try installing that plugin and check if it works.

**Comment by oliverkurth** [comment]
Per PM from @seamaner we can close this issue.
