### ISSUE TITLE
Clipboard share, drag&drop and auto resolution all don't work on fresh install OpenSUSE Leap 42.2 and VMWare workstation 12.5

### ISSUE THREAD

**Issue by runapp** [vmware/open-vm-tools#147]
What log should I post?

**Comment by planesweep** [comment]
Hi I have the same issue without any ideas to solve.

**Comment by oliverkurth** [comment]
I was not able to reproduce this in a fresh install of OpenSuSE 42.2 (with kde), with open-vm-tools that came with OpenSuSE (10.0.7) within WS 12.5. Can you please give more details about your environment?

What version of tools do you have installed? (output of "vmtoolsd -v")
Do you have (when logged into the gui) two vmtoolsd daemons running? (check with "ps awx | grep vmtoolsd")
If you are using rpm packages, do you have both open-vm-tools and open-vm-tools-desktop installed? (check with "rpm -qa | grep open-vm-tools")
If yo do not have open-vm-tools-desktop installed this would explain the symptoms.

**Comment by runapp** [comment]
Now it works. But I have to manually run `vmtoolsd -n vmusr` each time I log in.
However, the vmhgfs remains empty after setting shared folder and rebooting guest.
I tried open-vm-tools 10.0.7 and 10.1.0(from VMWare's repo).

**Comment by lousybrit** [comment]
Hi there,

I am the main developer the vmhgfs Shared Folders feature.

I think the kernel version you are running against is 4.4, is that correct?
("uname -r" should give you that)

If that is the case, then the kernel driver and mount are not going to work as for kernel versions 4.0 and newer we use a FUSE file system now. This has different mount commands.

First, check and verify that /mnt/hgfs folder exists. If not create it.
Second, then verify /usr/bin/vmhgfs-fuse exists.
Third, run "/usr/bin/vmhgfs-fuse --enabled" 
This last command should tell you that the Shared Folder file system is supported for this install.
It will tell if there is a problem, such as the kernel version is not compatible or that the FUSE packages are not installed.
Finally, run as root (or sudo) "/usr/bin/vmhgfs-fuse .host:/ /mnt/hgfs -o subtype=vmhgfs-fuse,allow_other"
Now check that the shares you have created appear under /mnt/hgfs

If all of the above is not correct because the kernel version is 3.x then check the following:
"lsmod |grep vmhgfs"
If that shows that vmhgfs is present then you do have the kernel driver loaded and running.
If it is not then there is an issue and you will likely need to run vmware-tools-config.pl script again to build and install it. Then recheck the driver is loaded as above. If there issues with that please report them.
Lastly do the mount you did previously, "sudo mount -t vmhgfs .host:/ /mnt/hgfs"
Again, verify the shares appear under /mnt/hgfs folder.

Hope this helps,
Steve

**Comment by oliverkurth** [comment]
@runapp 
> Now it works. But I have to manually run vmtoolsd -n vmusr each time I log in.

You can start the user process with the command
`vmware-user-suid-wrapper`
You can start it automatically by adding the file `/etc/xdg/autostart/vmware-user.desktop`, and adding the command there. On Ubuntu it looks like this, I believe it should work with OpenSuSE too:

```
[Desktop Entry]
Type=Application
Encoding=UTF-8
Exec=/usr/bin/vmware-user-suid-wrapper
Name=VMware User Agent
# KDE bug 190522: KDE does not autostart items with NoDisplay=true...
# NoDisplay=true
X-KDE-autostart-phase=1

```

The open-vm-tools-desktop package shipped by OpenSuSE should already have this.

I have answered a similar question at issue #150 , maybe that helps you too.

**Comment by runapp** [comment]
Thanks @oliverkurth

**Comment by runapp** [comment]
@lousybrit Seems caused by no `/mnt/hgfs` folder... I somehow remembered it exists. Maybe I got confused by multiple VM instances. Thanks for your patience.

**Comment by lousybrit** [comment]
There is a bug in that version of tools which can lead to the folder for the mount not being created automatically and thus causing the mount to fail for Fuse clients.

It has been addressed with the newest version of tools.
Glad that it is okay now.

Steve
