### ISSUE TITLE
gvaluetypes.c:455

### ISSUE THREAD

**Issue by epavser** [vmware/open-vm-tools#156]
Hello, 

I'm building open-vm-tools-10.1.5-5055683 from scratch.

Following flags has been used for "configure":
`./configure --disable-vgauth --disable-tests --disable-docs --without-x --without-procps --without-pam --without-xerces-c --without-icu --without-x --without-ssl`

It is successfully build, but I'm getting the following error when trying to run "vmtoolsd":

`**
GLib-GObject:ERROR:gvaluetypes.c:455:_g_value_types_init: assertion failed: (type == G_TYPE_CHAR)
Aborted (core dumped)`

Will be highly appreciated for any advises or thoughts.

**Comment by oliverkurth** [comment]
Thanks for reporting!

Can you please give some more information about your environment?
- which Linux distribution is this and which version?
- since this assertion fails in glib, which particular version of glib do you have installed?
- can you attach the output of the configure command, make and make install?

Ideally we can reproduce this issue here, so any additional information that you can think of would be helpful.

**Comment by oliverkurth** [comment]
I was asking for the glib version, not glibc. You can find out with
`pkg-config --modversion glib-2.0
`
Are all dependencies installed from source? Is there a reason that you are not using the Debian packages, or any package manager? Since open-vm-tools is part of Debian, the easiest way to install all build dependencies is with
`apt-get build-dep open-vm-tools`
Provided that you have
`deb-src http://ftp.us.debian.org/debian/ stretch main
`
in `/etc/apt/sources.list`. Of course that assumes that you use apt as a package manager.

If you built all dependencies from source, please make sure that you have the latest versions. You can list them all here. You can also install gdb, use the core file, print a stack trace, and post it here. Maybe that gives us a clue what call in open-vm-tools leads to the crash.

FWIW, I tested building open-vm-tools with the same options (in current Debian/sid), and it builds and runs fine.

**Comment by epavser** [comment]
Solved. 
Glib was historically build with (--enable-shared=no) as configure flag. Changing it to "yes" solved the issue.

Thanks.
