### ISSUE TITLE
SCSI-based Linux guests file systems becoming corrupted

### ISSUE THREAD

**Issue by CollinChaffin** [vmware/open-vm-tools#165]
I am reporting this here as well as (trying) to somehow get a case opened with VMware.  I apologize if this is determined to not be an issue with the open-vmtools, but because it is what is installed by default in all my test cases (and others also reporting this issue) I at least wanted to open it here for investigation.

# Issue Description:
Upon building a new Linux guest, in my case tested with both Ubuntu 16.04 LTS, 17.10, and Kali Linux 2017.1 on a Windows 7 x64 host, using VMware Workstation 12.54 & 12.55, after a power off and subsequent restart, the EXT4 guest filesystem becomes corrupted with random various errors, many times rendering the guest OS unusable.

Here is just one issue recently opened (and closed) on a Linux distro related tracker that perfectly mirrors the issue I have been fighting with for the last 24 hrs:

https://bugs.kali.org/view.php?id=4017#c6700

# Cause
Without being able to confirm WHY or the details, through sheer trial and error my testing mirrors that of the above Kali ticket that came to the conclusion that the root cause was the combination of the newer Kernel (exact cutoff not known but for instance Kali 1.09 was tested okay), and the default installed open-vm-tools, and the key being configuring the guest with the VMware-recommended choice of the SCSI virtual controller/driver.

# Workaround
Per the above testing, selecting the non-recommended default disk driver as SATA instead of SCSI appears to prevent the corruption.  It is not known, however, at this time if other drivers (USB) using SCSI drivers to communicate could also be at risk of corrupting the file systems of mounted volumes.

# Notes / Testing
Honestly, not being the Linux guru I would like to be has be at a great disadvantage as I do not even have a good grip on the exact driver names involved here.  I see mention that the open-vm-tools are relying now on "built-in" drivers and may not be installing all drivers, but again I am not convinced since vmware drivers were never present in the OS' in the past whether that simply means that older, static open-vm-tools drivers were provided to the OEM distro builders, etc. and still needs to be investigated.  Either way, this is a pretty big deal since it really is totally corrupting file systems.  I have not completed my testing to confirm whether manually installing the actual vmtools and removing the open-tools has any impact.  I am not even sure what or how to best debug here, but I will be happy to help provide any additional information I can to help.

**Comment by oliverkurth** [comment]
Thanks @CollinChaffin for reporting. Can you please give us more details about the setups, especially:
- what kernel version is used? (find out with `uname -a`)
- are you using the pvscsi driver shipped with the kernel (as recommended)? You can find out with the command `modinfo pvscsi`, which will also give the version (the driver shipped with the kernel will have -k at the end of the version)
- and the version of open-vm-tools (`vmtoolsd -v`)
This unlikely to be related to open-vm-tools. The pvscsi driver is not part of open-vm-tools.

**Comment by CollinChaffin** [comment]
root@ubuntu:~# uname -a
Linux ubuntu 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu:~# modinfo pvscsi
modinfo: ERROR: Module pvscsi not found.
root@ubuntu:~# vmtoolsd -v
VMware Tools daemon, version 10.0.7.52125 (build-3227872)

Sorry this guest was rebuilt now using SATA so I will have to rebuild another bad one perhaps today to verify but yes, should be the default scsi driver because I did NOT perform any additional vmtools installs in these test cases - just the guest OS of 16.04LTS out of box, with and without updates, and even the 17.x release just to see and all corrupt.  All those tests however instantly succeeded without any corruption with a rebuild using SATA disk in the guest.  In later tests I believe I also tested using the easy setup in workstation which I usually do NOT use pointing it at the supported 16.04 LTS ISO which it recognized and then default suggested the SCSI disk, and then re-ran it again overriding selecting SATA there.  In all cases I avoided ANY custom VMX config changes to keep the tests as pure as possible.

Sorry about the lack of above driver ver, wish I would have had run that modinfo on it prior to tearing the last corrupt one down, but since this is 100% reproducible easily, it's just a matter of an hour to build another.

**Comment by ravindravmw** [comment]
> after a power off and subsequent restart, the EXT4 guest filesystem becomes corrupted

If you are powering off the VM (aka hard power off) instead of shutting down guest, it is not surprising to get file system corruption. Please confirm and make sure that you are issuing guest shutdown either from WS UI or from within the guest.

I'd like to clarify that this is not related to open-vm-tools because Linux drivers are no longer considered as part of open-vm-tools. If shutting down guest does not resolve the file system corruption issue, it will require further diagnosis that would have to be done by VMware support. Also, it may be worth going through https://pubs.vmware.com/vsphere-65/index.jsp?topic=%2Fcom.vmware.vsphere.vm_admin.doc%2FGUID-5872D173-A076-42FE-8D0B-9DB0EB0E7362.html for a better understanding of storage adapters including the caution about changing controller type if you are doing that.

**Comment by CollinChaffin** [comment]
No sorry it's a graceful shutdown and power off via either gui or cmdline within the guest - I'm certainly not cold-cocking it and powering off, but good thought!

I don't disagree however I opened it here just to verify, and also because this HAS to be affecting others and if they come here which might be the logical choice, it's helpful for them to know.  I'm trying to get something opened with VMware too.  Since the behavior changes so radically when literally the only change is the guest disk driver from SCSI to SATA, and all other params remaining the same, and the fact that this behavior sure seems to be changing depending on the version of vmware workstation, and also then when coincidentally in the last 6 mo a major Linux issue similar to this was addressed at least partially in ESXi......it begs whether the same bit of bad code just hasn't yet been patched out of the workstation/player line yet.

Thanks again for taking a look!

**Comment by ravindravmw** [comment]
> when coincidentally in the last 6 mo a major Linux issue similar to this was addressed at least partially in ESXi......it begs whether the same bit of bad code just hasn't yet been patched out of the workstation/player line yet.

If you could share the details of the issue, I can try to check that. Do you have any reference to a VMware KB article or some other document for the issue you are referring to?

**Comment by CollinChaffin** [comment]
Sorry for the delay!

#88 & https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=51306

are two that bit me there might have been a third too in this last year that was Linux kernel specific and then I've also run across these on the vmxnet side as well which are newer kernel related:

https://bugzilla.kernel.org/show_bug.cgi?id=191201
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1650635

A colleague had mentioned there was a Linux kernel related patch to ESXi in the last year that he had come across which someone at vmware in the forums actually seemed like he was also referring to but I don't have the specifics (I'll try to get it though to update here)

**Comment by CollinChaffin** [comment]
EDIT; 

Just catching up and this thread also offers some insight along with a bunch of other users having similar issues and some with far more Linux expertise and sounds like have made a bit of progress since I've been offline.  No resolution yet but at least it is getting some attention:

https://communities.vmware.com/thread/565053?start=15&tstart=0

Which then refers to this recently found issue:

https://communities.vmware.com/thread/565157

Mind you this is not the exact disk corruption but also includes some other recent Linux kernel and ESXi and WS issues and it sure seems plausible that they could be connected.

**Comment by ukguy** [comment]
Interesting... we have just become aware during testing that all our replicas are corrupt, this includes Centos 6 and 7 and ext4 and XFS, it doesn't matter. Latest kernel now but this issue seems to have been around for at least 6 months and we didn't notice until we tested the replicas with a boot.

They all boot up with file inconsistencies, even though some have VMTools quiescing turned on. It's now being questioned if vmtools quiescing actually does anything.
The vm's start up needing to run fsck or xfs_repair which would severely delay any failover.

Noone currently have any conclusive answer. Many forums say quiescing is not needed in linux, crash consistent is ok, but in our case we'd prefer if the backups were consistent.
I tried running complete new replicas, they are still corrupt, so it happens as soon as a snapshot is taken.

Also if we repair with fsck, then when the next replica runs with incremental updates via vmware cdt, the replica is corrupt again. Therefore this seems to be directly related to vmtools and the quiescing.

I am continuing to research this but have put so many hours in now, work is suffering, if anyone has any insight I'd appreciate it. I wanted to add to this thread for anyone else who may be reading.

**Comment by ravindravmw** [comment]
@ukguy I think your issue is related to quiesced snapshot and different from this issue raised by @CollinChaffin.

My understanding of @CollinChaffin's issue is, it is about file system corruption at guest shutdown and therefore this does not involve VMTools quiescing the file system. Also, @CollinChaffin is using WS.

Quiesced snapshot depends on VMTools to quiesce the guest file systems. Let's track this discussion in issue #103.

We might find out that both the issues could be related to the same issue in Linux kernel, the way it is dealing with file system buffers during shutdown and quiescing. But, we don't know for sure at this time.

**Comment by ravindravmw** [comment]
@CollinChaffin sorry for the delay. It is either an issue with the driver being used in the guest (LSI Logic?) or the issue with the device emulation. This is certainly not related to VMware Tools and/or open-vm-tools. I have opened a VMware internal bug 2083043 to track it. Would you mind sharing your VM configuration (vmx file) from the affected VM and also open a support case with VMware to diagnose it further?

PS: Once you open a support case with VMware, please close this issue because we are tracking only open-vm-tools related issues here.

**Comment by ravindravmw** [comment]
As this issue is not related to open-vm-tools, I'm going to close it for now.

@CollinChaffin FYI I have opened a VMware internal bug 2083043. Please open a support case with VMware mentioning this bug number and provide vmware.log for the affected VM. Once you open a support case, more support data may be requested. Please note that bug 2083043 is not progressing at the moment due to lack of support data. Your co-operation on root causing this issue will be highly appreciated. Thanks!
