### ISSUE TITLE
Linux Mint 18.3 Cinnamon -- open-vm-tools not working

### ISSUE THREAD

**Issue by TheHellSite** [vmware/open-vm-tools#230]
I just installed a fresh vm with Linux Mint 18.3 Cinnamon.
I then tried installing open-vm-tools as follows....

Attempt 1
```
apt-get update
apt-get upgrade
reboot
apt-get install open-vm-tools-desktop
reboot
```
----> works fine

Attempt 2
```
apt-get update
apt-get install open-vm-tools-desktop
reboot
apt-get upgrade or apt-get dist-upgrade
reboot
```
----> after "apt-get upgrade" it still works
----> after "apt-get dist-upgrade" open-vm-tools are broken

Attempt 3
```
apt-get update
apt-get dist-upgrade
reboot
apt-get install open-vm-tools-desktop
reboot
```
----> installs fine, but doesn't work at all

The only error I get during all installs is the "run-vmblockx2dfuse.mount" error, but I know the workaround. This is because the open-vm-tools package in Linux Mint isn't up to date, right?

Before dist-upgrade
cinnamon version "3.6.6"
kernel version "4.10.0-38-generic"

After dist-upgrade
cinnamon version "3.6.7"
kernel version "4.10.0-38-generic"

**Comment by AppiePau** [comment]
Install it via the Software Manager (GUI) and you should be victorious! Good luck!

**Comment by oliverkurth** [comment]
The information given is not very helpful. What version of open-vm-tools is installed? What do you mean with "open-vm-tools are broken" - what symptoms do you see?

Since you see differences when using various combinations of upgrade/dist-upgrade/reboots , this is more likely an issue with the package as delivered by Ubuntu, so I recommend to bring this up with Ubuntu. See https://help.ubuntu.com/community/ReportingBugs .
