### ISSUE TITLE
is reboot required. 

### ISSUE THREAD

**Issue by Raminder01** [vmware/open-vm-tools#249]
do we need a reboot of the (RHEL 6.x & 7.x) VM after installing open-vmtools

**Comment by oliverkurth** [comment]
We don't officially support open-vm-tools for RHEL6. AFAIK, there is no rpm package for open-vm-tools for RHEL6, so I guess you have it built from source. Since we don't ship any (Linux) kernel modules with open-vm-tools, you just need to (re)start the user services.

For RHEL7, if you installed the package from the RHEL7 repository, there is no reboot required. To restart the vmusr service, you have to log out of your X session and log in again, or restart that service manually.

Let me know if you need more details.

**Comment by stanguturi** [comment]
Answers already provided in the previous comment by @oliverkurth Closing the issue.
