### ISSUE TITLE
usb dvb-c tuner hauppauge WinTV-dualHD problem

### ISSUE THREAD

**Issue by trayntab** [vmware/open-vm-tools#331]
hi guys,

i don't know if i'm right here. I have a problem with my hauppauge WinTV-dualHD dvb-c tuner. 

I use a vmware esxi 6.7 host and a vm with ubuntu 18.04.2 (open-vm-tools 10.3.0 build 8931395).

I configure the vm with the usb device and i can see this device in my vm. I installed the drivers via ppa from hauppauge and tvheadend.

The strange thing is that i can see the usb-tuners and configure them, but the channel scan can't find something (but the tuner led is blinking - whats is right). in tvheadend the bandwidth is 0. That is not correct.

i use the same config on a native ubuntu server system with the same install and config -  there are no problems.

i don't know if there is a problem with open-vm-tools....

but maybe you can help me? =)

best regards 
trayntab

**Comment by johnwvmw** [comment]
@trayntab 

Open-vm-tools does not have anything to do with USB device configuration or I/O.

A better place to ask you question would be at [.](https://communities.vmware.com/community/vmtn/developer/forums)    Since you are using ESXi 6.7, click on the tab "vSphere" and then on "Start a Discussion".

I would also suggest that you include the ESXi 6.7 build number as well as clarify whether your device is using USB-2 or USB-3.

Regards,

**Comment by johnwvmw** [comment]
Sorry, the URL was discarded from the response:

Start at https://communities.vmware.com/community/vmtn/developer/forums

**Comment by trayntab** [comment]
hey johnwvmw,

thank you very much for your answer!

I will try it at the vmware forum!

best regards 
trayntab
