### ISSUE TITLE
The return value of 'sscanf()' should be checked

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [vmware/open-vm-tools#364]
The return value of 'sscanf()' should be checked before continuing to execute the program
https://github.com/vmware/open-vm-tools/blob/a4dde45f5e281663efc2e1acbf1bba0dfb5bfce1/open-vm-tools/lib/misc/hostinfoPosix.c#L316

**Comment by dsouders** [comment]
Thank you for reporting this issue.

The lack of a return value check is intentional.  The sscanf() call at line 316 is for an optional 4th number in the OS version string returned from uname().  If the value is present, the value will be used.  Otherwise the sscanf() will fail and version->hostinfoOSVersion[3] will be left as '0' because 'version' was allocated with calloc().  Please refer to the comments at lines 293 and 308.
