### ISSUE TITLE
gcc 9 build issues on 10.3.10

### ISSUE THREAD

**Issue by cpaelzer** [vmware/open-vm-tools#367]
Hi,
since I found #330  this might already be ok for you going forward to v11.
I found a bunch of commits which kind of cover what I have written:
- commit 553d128348f311080e156519e9ac26a518c8579d
- commit c68172ef7f2d4f116078e2aba82986a8cab0b16e
- commit 19ca3e36f6f16842a54f6f297f3cafcabde2f384
- commit a7c141fc5278146b86c71502f60767962b752af7

But there seem to be a few more errors which didn't get fixes (that I have found) and that seem to be still present in the devel branch for v11.

Those are:
```
/<<PKGBUILDDIR>>/open-vm-tools/lib/include/vmware/tools/threadPool.h:93:13: error: static inline [-Werror]
   93 | G_INLINE_FUNC ToolsCorePool *
      |             ^~~~~~~~~~~~~~~
```

Fix per https://developer.gnome.org/glib/stable/glib-Miscellaneous-Macros.html#G-INLINE-FUNC:CAPS is to just replace it with "static inline". (worked for me).

For 10.3.10 I think I just pick the above if they apply and disable the new warnings if some are left. But for you to double-check and think about the G_INLINE_FUNC I filed this issue.

**Comment by dsouders** [comment]
Thank you for reporting this issue.

An internal bug has been filed to address the problem.

**Comment by thelounge-zz** [comment]
the quality of the whole codebase is a bad joke, proper software builds without any warnings

-Wno-unused-local-typedefs -Wno-deprecated-declarations -Wno-unused-function -Wno-sizeof-pointer-memaccess -Wno-error=address-of-packed-member -Wno-error=format-overflow

**Comment by thelounge-zz** [comment]
i am not a C/C++ developer but annoyed that open-vmtools has the worst code qualitiy of all software i build from source over the last 15 years

**Comment by stanguturi** [comment]
Check 89c0d444567eb525e8d083fb564c46d68e96660c That should solve the issue.

Thanks

**Comment by edrozenberg** [comment]
For some reason the fixes in 89c0d44 are not present in current master or in open-vm-tools-11.0.5-15389592.tar.gz which I just downloaded, causing me to run into the same build error under gcc9. I'll have to create my own patch and apply it.

**Comment by oliverkurth** [comment]
Yes, that change did not make it into the stable-11.0.x branch. `master` is always synced to the last release. It will be in our next release though.

**Comment by thelounge-zz** [comment]
well, i use patches from left and right all the time but is it *really* that hard to fire code automated against recent compilers and fix f**g warnings *before* they become errors?

my quality line of our 250000 LOC codebase in case of php software is

a) every notice or warnings is a fatal error and has to be fixed
b) the whole autotests and deplyoments have to be fired against 7.2/7.3/7.4/HEAD aka 8.0-dev
c) any warning which is not clearly a wrong behavior in upstream HEAD has to be fixed *now*

and man i maintain that stuff as a one man show since 2003 with the same "every notice is a error" attitude and you are a big company too dumb to read and fix compiler outputs with -Wall

**Comment by ravindravmw** [comment]
We don't expect users of open-vm-tools to spend effort in building it because pre-built packages are provided along with all major distros (Fedora included) and also from the distro specific repository. Distro provided open-vm-tools comes with combined support from the distro and VMware. The only people who need to build open-vm-tools are either virtual appliance developers, users of distros that don't have open-vm-tools included or open-vm-tools contributors.

Sorry to hear about the product issues you are facing. As this forum is intended for open-vm-tools related issues only, please consider opening support cases with VMware Support for all the issues you are facing with other VMware products. VMware Support should be able to take up your cases with the right engineering teams and get you appropriate help.

**Comment by thelounge-zz** [comment]
besides that your support wasn't able to solve any issue in the past 12 years and even recommends install a NIC driver from a older ESXi version instead just enable it when it#s part of the base image  i consinder distro packages when they stop pull a ton of useless dependencies for guests far below 500 MB total disk usage

%configure --quiet --disable-static \
 --disable-caf \
 --disable-deploypkg \
 --disable-docs \
 --disable-grabbitmqproxy \
 --disable-multimon \
 --disable-tests \
 --disable-vgauth \
 --with-gnu-ld \
 --with-pic \
 --without-dnet \
 --without-gtk2 \
 --without-gtk3 \
 --without-gtkmm \
 --without-gtkmm3 \
 --without-icu \
 --without-kernel-modules \
 --without-pam \
 --without-procps \
 --without-root-privileges \
 --without-x \
 --without-xerces \
 --without-xml2 \
 --without-xmlsec1 \
 --without-xmlsecurity

[root@buildserver:~]$ rpm -q --filesbypkg open-vm-tools  | grep -v build\-id
open-vm-tools             /etc/vmware-tools
open-vm-tools             /etc/vmware-tools/poweroff-vm-default
open-vm-tools             /etc/vmware-tools/poweron-vm-default
open-vm-tools             /etc/vmware-tools/resume-vm-default
open-vm-tools             /etc/vmware-tools/scripts
open-vm-tools             /etc/vmware-tools/scripts/vmware
open-vm-tools             /etc/vmware-tools/scripts/vmware/network
open-vm-tools             /etc/vmware-tools/statechange.subr
open-vm-tools             /etc/vmware-tools/suspend-vm-default
open-vm-tools             /etc/vmware-tools/tools.conf.example
open-vm-tools             /etc/vmware-tools/vm-support
open-vm-tools             /usr/bin/vmtoolsd
open-vm-tools             /usr/bin/vmware-checkvm
open-vm-tools             /usr/bin/vmware-namespace-cmd
open-vm-tools             /usr/bin/vmware-rpctool
open-vm-tools             /usr/bin/vmware-toolbox-cmd
open-vm-tools             /usr/bin/vmware-xferlogs
open-vm-tools             /usr/lib/systemd/system/vmtoolsd.service
open-vm-tools             /usr/lib/udev/rules.d/99-vmware-scsi-udev.rules
open-vm-tools             /usr/lib64/libguestlib.so.0
open-vm-tools             /usr/lib64/libguestlib.so.0.0.0
open-vm-tools             /usr/lib64/libhgfs.so.0
open-vm-tools             /usr/lib64/libhgfs.so.0.0.0
open-vm-tools             /usr/lib64/libvmtools.so.0
open-vm-tools             /usr/lib64/libvmtools.so.0.0.0
open-vm-tools             /usr/lib64/open-vm-tools
open-vm-tools             /usr/lib64/open-vm-tools/plugins
open-vm-tools             /usr/lib64/open-vm-tools/plugins/common
open-vm-tools             /usr/lib64/open-vm-tools/plugins/common/libvix.so
open-vm-tools             /usr/lib64/open-vm-tools/plugins/vmsvc
open-vm-tools             /usr/lib64/open-vm-tools/plugins/vmsvc/libguestInfo.so
open-vm-tools             /usr/lib64/open-vm-tools/plugins/vmsvc/libpowerOps.so
open-vm-tools             /usr/lib64/open-vm-tools/plugins/vmsvc/libresolutionKMS.so
open-vm-tools             /usr/lib64/open-vm-tools/plugins/vmsvc/libtimeSync.so
open-vm-tools             /usr/lib64/open-vm-tools/plugins/vmsvc/libvmbackup.so
open-vm-tools             /usr/share/open-vm-tools

**Comment by thelounge-zz** [comment]
oh and get rid of these ones would be nice too:

open-vm-tools /usr/lib64/libhgfs.so.0
open-vm-tools /usr/lib64/libhgfs.so.0.0.0

**Comment by ravindravmw** [comment]
Looks like, you don't need "open-vm-tools-desktop" package. Have you compared disk footprint of your custom build with "open-vm-tools" package's disk footprint? If difference is not significant, you may consider using it as-is.

**Comment by thelounge-zz** [comment]
besides that it don't make bad code quality better just because someone else compiles it these packages required by the fedora rpm aren't even installed on our buildserver which provides a cache repo containing all the 1218 packes in total used on the whole cluster

production vms are stripped down to a total of 269 packages at all

no, thanks!

  - nothing provides fuse needed by open-vm-tools-11.0.5-2.fc31.x86_64
  - nothing provides libxmlsec1.so.1()(64bit) needed by open-vm-tools-11.0.5-2.fc31.x86_64
  - nothing provides xmlsec1-openssl needed by open-vm-tools-11.0.5-2.fc31.x86_64
