### ISSUE TITLE
stat balloon support on workstation?

### ISSUE THREAD

**Issue by Akababa** [vmware/open-vm-tools#379]
Would it be at all possible to support the `vmware-toolbox-cmd stat balloon` and other commands on Workstation Player/Pro? Documentation on this is also lacking as I only found it was only supported on ESXi from from [this old document](https://www.vmware.com/pdf/vmware-tools-cli.pdf) after a couple hours of debugging "vmware guest api is not enabled on the host".

**Comment by lemke1458** [comment]
The stat commands only apply to ESX; Workstation doesn't support them.

Are you asking for these statistics to be available on Workstation?  What's the use case?

**Comment by lemke1458** [comment]
These cmdlets are built on RPCS between the guest and the VMX.  When the VMX doesn't support something (eg Workstation and stats), then there's no code for it in the VMX, and it won't recognize the RPC.  Tools is agnostic to the underlying platform, and doesn't attempt to have any logic for this -- it issues the RPC, and in this case gets an error.

**Comment by stanguturi** [comment]
Thanks @lemke1458 for the explanation.

We have already documented the exit codes for 'VMware Tools toolbox utility'.

https://docs.vmware.com/en/VMware-Tools/10.2.0/vmware-tools-user-guide.pdf

'''
75     stat            The host does not support the query, perhaps because the
                            host is not an ESX/ESXi host (EX_TEMPFAIL).
'''

Closing this bug.
