### ISSUE TITLE
Question about what executable is engaged in C&P (copy-and-paste) function through VMWare

### ISSUE THREAD

**Issue by 4hm3dh4ny** [vmware/open-vm-tools#397]
I am creating a filter to prevent copying files from host os to vmware workstation guest os..
now all things is fine as I am monitoring "vmware-vmx.exe" executable..

but the strange thing is: when the guest machine is windows 10 (or even windows 8.1) the files evades the filter.. and that is not the case for windows 7..

I tried to search and ask everywhere.. also tried to use api monitoring solutions to detect the C&P opertaion happens through which executable but no luck till now.

**Comment by jonathanvmw** [comment]
Can you provide more details about what you are trying to do?  For example, what do you mean by "creating a filter?"  What specific behavior are you seeing when the guest is Windows 10?  When it's Windows 7?  Also, what version of workstation are you using, and what host type?  What version of vmware tools is running on each guest?

Thanks.

**Comment by ahm3dhany** [comment]
Thank you @johnwvmw 

General Details:
Vmware Workstation version: 15.5.0 (latest version)
Vmware tools version: 11.0.0.15108 (build-14549434) [the same version across all the VMs]

More Details:
- The filter that I'm trying to create is a kind of DLP (Data Leakage Prevention) filter.
- It doesn't matter what the guest OS version (the behavior is the same across Win 10, Win 8.1, Win 7 & Win XP [those are the versions I tried]).
- The problem with the Host OS.. the behavior is different between Win7 and all newer version of windows (e.g. Win 8.1 & Win 10).
- The strange behavior is that:
  - In case of windows 7... when copying a file from Host OS to Guest OS, the paste operation happens through "vmware-vmx" executable -> so that my filter is able to detect it.
  - In case of newer OS (like Win 10 or 8.1), the paste operation didn't happen through "vmware-vmx" executable.. so I need to know how the paste operation is done (specifically which executable it goes through).

**Comment by 4hm3dh4ny** [comment]
Thank you @johnwvmw 

General Details:
- Vmware Workstation version: 15.5.0 (latest version)
- Vmware tools version: 11.0.0.15108 (build-14549434) [the same version across all the VMs]

More Details:
- The filter that I'm trying to create is a kind of DLP (Data Leakage Prevention) filter.
- It doesn't matter what the guest OS version (the behavior is the same across Win 10, Win 8.1, Win 7 & Win XP [those are the versions I tried]).
- The problem with the Host OS.. the behavior is different between Win7 and all newer version of windows (e.g. Win 8.1 & Win 10).
- The strange behavior is that:
    - In case of windows 7... when copying a file from Host OS to Guest OS, the paste operation happens through "vmware-vmx" executable -> so that my filter is able to detect it.
    - In case of newer OS (like Win 10 or 8.1), the paste operation didn't happen through "vmware-vmx" executable.. so I need to know how the paste operation is done (specifically which executable it goes through).

**Comment by jonathanvmw** [comment]
@4hm3dh4ny,

There is apparently a difference between how Windows 7 and Windows 10 implement copy and paste.  Specifically, in Windows 7, when copying a file, the clipboard includes the file path, while in Windows 10 the clipboard may additionally include the file contents.  If Workstation detects that the clipboard includes file contents, and the file size is less than 4 Mbytes, then the file I/o will be done by the “vmware” executable; otherwise the I/o is done by the “vmware-vmx” executable.

Given your observations of Windows 8.1 behavior, presumably Windows 8.1 also may sometimes include file contents in the clipboard when doing a file copy and paste.

Please bear in mind that this is implementation-dependent behavior and subject to change, and anything you develop that relies on the current behavior may no longer work if the implementation changes.

**Comment by 4hm3dh4ny** [comment]
Again thank you @jonathanvmw  for these useful & detailed info. I am very grateful for your help.
Is there any documentation which I could find this info and read more about it?

**Comment by jonathanvmw** [comment]
Descriptions of Windows clipboard formats, with additional links to related information:

https://docs.microsoft.com/en-us/windows/win32/shell/clipboard
https://docs.microsoft.com/en-us/windows/win32/dataxchg/standard-clipboard-formats

Program to dump the clipboard contents:

http://www.freeclipboardviewer.com/

Program to monitor process activitiy, including file i/o:

https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

For instance: The clipboard viewer can be used to compare the clipboard contents for different copy-paste operations, such as on different host types, file sizes and/or types, single-file, multi-file, and directory operations.  The clipboard format information is useful for understanding clipboard viewer output.  Procmon can be used to show, among other things, which processes are doing i/o to or from which files.

(Again, though, please be cautious about relying on undocumented behavior which is subject to change.)

**Comment by 4hm3dh4ny** [comment]
Thank you sir.. You've been very helpful!
