### ISSUE TITLE
[ warning] [guestinfo] GuestInfoGetDiskDevice: Missing disk device name; VMDK mapping unavailable for "/", fsName: "/dev/sda2"

### ISSUE THREAD

**Issue by slavaua-tech** [vmware/open-vm-tools#404]
After updating open-vm-tools 11.0.1 errors began to appear in the logs: vmare-vmsvc-root.log , they are recorded every minute:

 
[ warning] [guestinfo] GuestInfoGetDiskDevice: Missing disk device name; VMDK mapping unavailable for "/", fsName: "/dev/sda2"

 

How to solve a problem?
 

Ubuntu 18.4.3

ESXI 6.7.0 Update 3 (Build 15160138)

**Comment by johnwvmw** [comment]
This is a known problem that was just reported on other Linux releases.

The issue is triggered when "SCSI controller 0" happens to be a LSI Logic Parallel SCSI controller and it gets enumerated on PCI bus 0.  The controller name is not populated in the /sys/class/blocks PCI information.

Option 1: Switch to the VMware Paravirtual SCSI controller
------------------------------------------------------------------
   If your VM virtual hardware is new enough (I know that version 13 and later works), simply switch the "LSI Logic Parallel" controller at "SCSI controller 0" to "VMware Paravirtual" by editing the VM settings - with your guest VM safely shutdown.

Option 2: Change the logging level for vmsvc to avoid warning messages.
---------------------------------------------------------------------------------
Edit the /etc/vmware-tools/tools.conf file, changing the 
   #vmsvc.level = debug
to 
   vmsvc.level = critical

A patch for open-vm-tools 11.0.x has been prepared and tested for the same problem reported against a SUSE guest and is available at 
   https://github.com/vmware/open-vm-tools/tree/stable-11.0.5-suse-bug-1162435/open-vm-tools

**Comment by johnwvmw** [comment]
P.S.   

Forgot to mention that that patch applies to the open-vm-tools source release for 11.0.0, 11.0.1 and 11.0.5.
