### ISSUE TITLE
Change owner of the vmware logs in /var/log

### ISSUE THREAD

**Issue by ConstantinJean** [vmware/open-vm-tools#473]
Hi,

Is it possible to change the ownership/permissions of the vmtools log files in /var/log? Meaning vmware-network.log and vmware-vgauthsvc.log.0 vmware-vmsvc.log
Some user process needs read access to those and they are owned by root by default. 
I saw for the network logs it is a bash script in /etc/vmware-tools/scripts/vmware/ but I am not sure I should touch it as it might get overwritten when the next update comes.
As for the other logs, the permissions seem to be hardcoded in the source files.

Is there a way to change the owner, maybe in the tools.conf?

Thanks!

**Comment by lemke1458** [comment]
Yes, for security reasons the logs are unreadable.  Potentially sensitive data like hostnames, filenames, IP address, etc can be logged, especially if the logging level is changed to be more verbose.

Changing this would require code changes.

**Comment by johnwvmw** [comment]
And the network script would be overwritten with the next open-vm-tools update.

Can you share what information from these log files the "user process" is looking for?

Also what Linux guests OSs are involved?

**Comment by ConstantinJean** [comment]
I am not very fond of the design made, but from a java program running as an unprivileged user, an rsync command is called that copies all the logs to another secure place. We could change owner/permissions on the syslog logs, mongoDB but not for VMtools.
They want the entirety of the logsin /var/log to be sent via rsync for post analysis purposes in case any issue arises in this confined environment.

**Comment by johnwvmw** [comment]
I realize that it is possible to change the system default log file permissions by the configuration in /etc/logrotate.d/, but I would expect a security audit would wave a red flag if and when the log files are seen as world readable.

The network script is used each time VMs are powered on/off, suspended and resumed.  The script does not have the knowledge to read and parse the tools.conf file.  Nor would it be desirable for it to take the time to do so during these power operations.

I wonder if either of the following may work?

1. Instead of the java program executing rsync directly, execute a setuid script that does the rsync to a secure location and changes the owner/permissions of those copied files.

2. If SELinux is enabled on the Linux VMs, explore adding a SELinux context (users, roles) that will grant access to the root user owned read-only files of interest.

**Comment by jlgaddis** [comment]
> They want the entirety of the logsin /var/log to be sent via rsync for post analysis purposes in case any issue arises in this confined environment.

@ConstantinJean,

In my opinion, your "best" option would be to configure the various services to log via `syslog` (instead of them writing to their own log files in `/var/log`).

By using the `syslog` daemon (`rsyslog`, `syslog-ng`, etc.) that's already being used on the host, you gain the ability to decide where the log messages actually go -- to the default/standard log files in `/var/log`, to separate, per-service log files (in `/var/log` or elsewhere), to a central loghost in your network, or anywhere else you may want them to be sent.

Additionally, assuming that "`logrotate`" is being used on the host, **you will also be able to control the ownership and permissions of the log files**, if and/or when they get rotated, and so on.

If you wanted to, you could even trigger an automatic `rsync` immediately after the logs are rotated (via `logrotate`'s "`postrotate`" option) -- although, speaking with my security nazi hat on, it would be better to "pull" the log files from the other host<sup>1</sup>.

Personally, I have yet to encounter any downsides (YMMV!) and I think this would give you that extra bit of control over logging that you need. The [example "`tools.conf`" file](../blob/master/open-vm-tools/tools.conf#L84) explains how to configure the various services to log via `syslog`.

Alternatively, you may want to become familiar with `setfacl(5)` and ACLs.

---

[1]: Of course, "the best way" to preserve a copy of the logs "for post analysis purposes in case any issue arises" would be to send them, in real-time, to a centralized log host (over a TLS-encrypted channel) but that's an entirely different discussion.

**Comment by ConstantinJean** [comment]
Hello, thank you for your feedback! 
We already have splunk sending some logs from that machine and I don't really understand the requirement to do it the way we do it.
Thank you for all these details on how to go about it, I am sure one of these solution will be allowed by our security team. I have enough to close the issue 🙂
