### ISSUE TITLE
make  /open-vm-tools/vgauth/lib/authPosix.c:355: undefined reference to `crypt'

### ISSUE THREAD

**Issue by gprime31** [vmware/open-vm-tools#481]
/open-vm-tools/vgauth/lib/authPosix.c:355: undefined reference to `crypt'
how do i fix this?

**Comment by lemke1458** [comment]
Ah, I didn't know William had put that out.  We have some suggestions on how to improve his build suggestion, so hopefully he'll update with those.

You'd want to turn PAM on to avoid that compile error.

If PAM isn't used, -lcrypt needs to be in the link line.  I suspect that's a bug in our configure.ac that nobody has tested, because the crypt() code path is there for backwards compatibility.

**Comment by gprime31** [comment]
Ok, I'll try it when I get off work and let you know, thanks

**Comment by lemke1458** [comment]
Be sure you got libpam0g-dev; lack of that may have been what turned PAM off.

**Comment by gprime31** [comment]
Will do, I'm running debian 10 arm64 just so you know.

**Comment by gprime31** [comment]
Ok so no change with libpam0-dev installed but like I said with -f it still works.

**Comment by stanguturi** [comment]
Check 30a9f295681983c778ea89eef379b8822518e524 submitted on devel branch. --without-pam option can be used to disable VGAuth and this error will not be reported. Closing this issue.
