### ISSUE TITLE
CentOS 7 guest customization not working with open-vm-tools 9.10.2-4

### ISSUE THREAD

**Issue by power13** [vmware/open-vm-tools#56]
I installed a VM with CentOS 7, installed open-vm-tools 9.10.2-4 and wrote Red Hat Enterprise Linux Server release 7.0 (Maipo) to /etc/redhat-release. Then I converted the VM to a VM template.

If I deploy a VM from this template with guest customization there is no error during deployment but the VM is not customized.

But as I have seen here: https://github.com/vmware/open-vm-tools/issues/9 the guest customization should work with open-vm-tools 9.10 without open-vm-tools-deploypkg.

Does this work for anybody?

**Comment by molixrawdi** [comment]
Hi,
      Saltstack is failing to deploy as a result of this update, any is any one aware of a fix! Can I still find version 9.4 any where!

**Comment by aneverov4vmw** [comment]
Hi,

When executed, guest customization produces log files in /var/log/vmware-imc/* folder. If the files are not there (or are not updated in case they were there before), it means a deployPkg problem. Otherwise, the log will contain detailed information about what OS has been detected and how did different stages of the customization process go. Also it's useful to look at vCenter events for that VM (e.g. was there a Started and/or Error event?).

Could you please share those logs?

**Comment by power13** [comment]
Thanks for your help. As I have seen in the log you mentioned, perl was not installed. After perl was installed, Guest Customization works now.

**Comment by ravindravmw** [comment]
We need to add perl as a dependency to the package to avoid this in future.

**Comment by bby-bishopclark** [comment]
Found this, 2+ years later for a similar issue, filed a ticket on RH BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1539802 .  I didn't find the packaging here so I went there.

**Comment by bby-bishopclark** [comment]
I'm really sure it's not SaltStack-specific, this bug, and should be expected to affect Puppet, Chef and all their peers.

RH has a tech note (badly in need of an edit) here:  https://access.redhat.com/solutions/2456451 .  It's behind a paywall, but basically says "Oh, not working?  Install perl"

So there's that, even if it does, uh, attract thoughts.

**Comment by drawsmcgraw** [comment]
@bby-bishopclark Definitely agree that it's not related to Saltstack. I suppose I could have just left out that detail.

> So there's that, even if it does, uh, attract thoughts.

So gracefully put :)

Does that mean that there's not much we can do on this side of things?

**Comment by ravindravmw** [comment]
Is upgrading CentOS an option for you guys? We may have a solution in a future CentOS update.

**Comment by drawsmcgraw** [comment]
@ravindravmw Upgrading would be fine for me but, in our case, we've already implemented the workaround (install perl).

Would the future CentOS update would work for 'clean' installs? Would we be able to take a clean CentOS machine and just install `open-vm-tools`? That's what I'm more concerned about.

Thanks for the quick response!

**Comment by bby-bishopclark** [comment]
Even if we can't upgrade, some of us are confident and practiced at running, say, EL68 with 2 packages from EL69 because of #badReasons.  There is trending, but it's still an option to do the same where I have CentOS installed.  Can we anticipate a fix for (eg) RHEL74EUS (with/out a support ticket) ?

**Comment by ravindravmw** [comment]
> Would the future CentOS update would work for 'clean' installs? Would we be able to take a clean CentOS machine and just install open-vm-tools?

Some configuration changes may be needed depending on what gets done before the release. However, we have plans to make it work out-of-the-box eventually.

> Can we anticipate a fix for (eg) RHEL74EUS (with/out a support ticket) ?

Actually, we are working towards a solution to get rid of the Perl dependency and I believe patching existing ones would be hard and you may need to continue installing Perl manually on existing versions.

**Comment by bby-bishopclark** [comment]
> patching existing ones would be hard
Nah.  I saw the ticket.  The problem is the mini respins not wanting Perl dragged in.  It's like how we also need EPEL for RHSat5 because of one module.  Hey, I'm fine with that, even if it is a
`sed -i /^%prep/Ii\Requires: perl/' /path/to/open-vm-tools.spec`
or so.  I did stuff far, far, faaarr worse at OpenLinux  ;-) 

What's the hoped-for time frame of a fix, and what will its nevra be?  Just for people searching it up later.

**Comment by hangrao** [comment]
@bby-bishopclark  Did you try:
1. make sure cloud-init is installed;
2. Add ‘disable_vmware_customization: false’ to /etc/cloud/cloud.cfg  (this is to allow customization to use cloud-init as the customization engine rather than perl.)

**Comment by drawsmcgraw** [comment]
Thanks @ravindravmw. It sounds like y'all have a solution in mind, which is encouraging. I think I could have worded my earlier response better. 

I'm just looking for the use case where I can reliably install `open-vm-tools` and have it Just Work. Personally, I don't care about the Perl requirement. If it's needed, then it's needed (though, again, I understand that's a personal matter). I'd much rather install Perl than have silent failures.

**Comment by drawsmcgraw** [comment]
@ravindravmw I see we've hijacked this issue. Would it be helpful if I were to open a new issue to address the Perl dependency specifically?
