### ISSUE TITLE
Clipboard share between Xubuntu 18.04 (guest) and Windows 10 (host) not working

### ISSUE THREAD

**Issue by svanimisetti** [vmware/open-vm-tools#566]
### Describe the bug

When running Xubuntu 18.04.3 VM in VMware Workstation 16 player, I am unable to copy-paste from Windows 10 host to Xubuntu. The clipboard is not shared even after installing open-vm-tools.

### Reproduction steps

```bash
1. Create a VM using Xubuntu 18.04 (install using [netboot mini.sio](http://archive.ubuntu.com/ubuntu/dists/bionic/main/installer-amd64/current/images/netboot/mini.iso)).
2. After the installation completes, install open-vm-tools using `sudo apt-get install open-vm-tools`.
3. Create a test file on Xubuntu desktop (right-click -> Create Document -> Plain Text) and open in any text editor (I used Geany).
4. Copy text from Windows 10 and try to paste into the text editor - and the text is not copied.
```

### Expected behavior

Text from Windows 10 should copy over to Xubuntu. Also, I do not see this issue when I using Ubuntu Desktop 18.04 - so I am assuming that this is a Xubuntu/Xfce specific issue.

**Comment by johnwvmw** [comment]
@svanimisetti  Please post the output of step #3 above.   That will determine the next steps that can be taken.

**Comment by svanimisetti** [comment]
@VinodKumarGoku - thanks for your suggestion. It is working as expected now. Do I have to always install `open-vm-tools-desktop` in place of `open-vm-tools` on all desktop/UI based Ubuntu flavors?

@johnwvmw - output form step3 above is as follows:

```
vmuser@xubuntu:~/Desktop$ ps -ef | grep vmtoolsd
root        582      1  0 10:02 ?        00:00:00 /usr/bin/vmtoolsd
root        999      1  0 10:02 ?        00:00:00 /usr/sbin/vmtoolsd
vmuser     1331      1  0 10:03 ?        00:00:00 /usr/bin/vmtoolsd -n vmusr --blockFd 3
vmuser     1480   1470  0 10:03 pts/0    00:00:00 grep --color=auto vmtoolsd
```

**Comment by svanimisetti** [comment]
Installing `open-vm-tools-desktop` instead of `open-vm-tools` resolved the issue.

**Comment by johnwvmw** [comment]
If you are using a graphical desktop, then yes, you should always install open-vm-tools-desktop on Linux releases.   That package has a dependency on open-vm-tools which will get installed prior to installing the desktop package.

If the Linux ISO is installed using the Easy Install option on hosted products, Easy Install will automatically install the open-vm-tools-desktop and open-vm-tools packages.    Since your setup was using an Xfce desktop, I assume that you did not use Easy Install and did an interactive install yourself.
