### ISSUE TITLE
[Question] Rocky and Alma major versions not listed in guest_os.h and guest_os_tables.h in devel branch

### ISSUE THREAD

**Issue by nazunalika** [vmware/open-vm-tools#572]
### Is your feature request related to a problem? Please describe.

Pull request #513 was closed recently, which would've added Rocky 8 and Rocky 9 to open-vm-tools in the master branch. This issue is more of a question to how the code will work for the next open-vm-tools major version.

Looking into the devel branch of open-vm-tools, we can see that both Rocky and Alma are listed in the guest_os and guest_os_tables headers. Unfortunately, compared to RHEL, CentOS, and Oracle Linux (and other distributions like sles, Amazon Linux, or even non-Linux distributions like Darwin), there are major versions explicitly tied to them. It is not clear if having Rocky and Alma generic is helpful to vmware plus its products and the enterprise linux ecosystem as a whole or if there are implications of doing so.

See "additional context" for code snippets of the headers in question.

### Describe the solution you'd like

Preliminary review of the devel branch lead to some thoughts that come to mind:

* It is not clear if this is by design and if there are benefits of keeping the ID's generic

As Rocky and AlmaLinux both follow RHEL (as much as Oracle Linux does and CentOS did in the past), it would make sense that they also have major versions assigned to them, eg `ROCKY8` and `ROCKY9`. Even CentOS 9 stream is listed with major versions. Though oddly, only RHEL 9 is listed and there's no signs of RHEL 8.

I also do not see anything that ties the derivatives in with how RHEL, CentOS, and Oracle Linux operate as enterprise linux distributions.

* Both Rocky and Alma are listed as `ALL5X...` which implies (to me and likely others) kernel 5. Rocky and Alma 8 are kernel 4. Rocky and Alma 9 will be kernel 5 just like RHEL 9 and CentOS 9 stream.

The question that comes from this is: How does this affect users? How does this affect the underlying infrastructure of vmware products? Is there a net positive from using just generic ID's as opposed to tying down to major versions?

-- --

Solution(?): 

* The addition of major versions tied into Rocky and Alma as they follow RHEL as downstream community distributions

and/or ...

* A possible explanation on the pros/cons of generic listing for Rocky and Alma when CentOS, Oracle, and RHEL (only 9) all have major versions tied to their ID's in the code

I am not sure there is a "solution" for this. But hopefully we can get an answer or an explanation on how this works.

### Additional context

```
   GOT(GUEST_OS_ORACLE)                                                    \
   GOT(GUEST_OS_ORACLE_64)                                                 \
   GOT(GUEST_OS_ORACLE6)                                                   \
   GOT(GUEST_OS_ORACLE6_64)                                                \
   GOT(GUEST_OS_ORACLE7_64)                                                \
   GOT(GUEST_OS_ORACLE8_64)                                                \
   GOT(GUEST_OS_ORACLE9_64)                                                \
   GOT(GUEST_OS_CENTOS)                                                    \
   GOT(GUEST_OS_CENTOS_64)                                                 \
   GOT(GUEST_OS_CENTOS6)                                                   \
   GOT(GUEST_OS_CENTOS6_64)                                                \
   GOT(GUEST_OS_CENTOS7_64)                                                \
   GOT(GUEST_OS_CENTOS8_64)                                                \
   GOT(GUEST_OS_CENTOS9_64)                                                \
```

Derivatives do not have major versions tied to them:

```
   GOT(GUEST_OS_ROCKY_LINUX_64)                                            \
   GOT(GUEST_OS_ROCKY_LINUX_ARM_64)                                        \
   GOT(GUEST_OS_ALMA_LINUX_64)                                             \
   GOT(GUEST_OS_ALMA_LINUX_ARM_64)
```

```
#define ALL4XLINUX64          BS(OTHER4XLINUX_64), BS(PHOTON_64),       \
                              BS(CENTOS8_64),      BS(CENTOS9_64),      \
                              BS(ORACLE8_64),      BS(ORACLE9_64),      \
                              BS(CRXSYS1_64),      BS(CRXPOD1_64),      \
                              BS(AMAZONLINUX2_64), BS(AMAZONLINUX3_64), \
                              BS(LINUX_MINT_64)

#define ALL5XLINUX32          BS(OTHER5XLINUX)

#define ALL5XLINUX64          BS(OTHER5XLINUX_64), BS(OTHER5XLINUX_ARM_64), \
                              BS(DEBIAN_ARM_64),   BS(UBUNTU_ARM_64),       \
                              BS(RHEL9_64),        BS(RHEL9_ARM_64),        \
                              BS(ROCKY_LINUX_64),  BS(ROCKY_LINUX_ARM_64),  \
                              BS(ALMA_LINUX_64),   BS(ALMA_LINUX_ARM_64)
```

**Comment by johnwvmw** [comment]
Let me assure you that Rocky Linux and others are not being short-changed in the level of support and recognition given by VMware Hypervisors.

Rocky Linux is picking up where CentOS leaves off, but that is not a reason to continue GOSIDs with major release version numbers tied to them when it is no longer needed.

Going forward VMware is phasing out use of versioned Linux GOSIDs because of low benefit vs cost to maintain.  Please take notice that Ubuntu, Fedora and VMware's Photon OS have always had generic GOSIDs.

And those low benefit and cost to maintain apply to the customer as well.

low benefit:
  - Separate Rocky 8 vs. Rocky 9 GOSIDs would only be visible to users on the vSphere Client UI VM Summary.  It only hints at the likely major release numbers when seen in the vSphere Client UI.

cost to maintain:
  - When Rocky 8 VMs are eventually upgraded to Rocky 9, the vSphere Client will still display "Rocky Linux 8".  The user will need to power off the VM, edit settings and change the Guest OS setting to "Rocky Linux 9".
 
Use of a generic Rocky Linux designation will ease things for your customer base.

Specific OS version information is assembled with a new API that will access the contents of "/etc/os-release" ("/etc/lsb-release" in older Linux OS) to produce a "guestInfo.detailed.data" string that is added to the VM configuration file (*.vmx).

That setting can be viewed from the vSphere Client UI by selecting:

```
 Edit Settings                                  Edit Settings
    -> VM Options                                -> VM Options
      -> Advanced                                   -> Advanced Parameters
        -> Configuration Parameters
```

With ESX 7.0 and running open-vm-tools 11.2.5, Rocky Linux 8.5 configured as "other4xlinux-64" gets:

**ESX 7.0.0**
  guestOS.detailed.data  = "bitness='64' distroName='Rocky Linux' distroVersion='8.5' familyName='Linux' kernelVersion='4.18.0-348.el8.0.2.x86_64' prettyName='Rocky Linux 8.5 (Green Obsidian)'"

**ESX 8.0.0**
  guestInfo.detailed.data = "architecture='X86' bitness='64' distroName='Rocky Linux' distroVersion='8.5' familyName='Linux' kernelVersion='4.18.0-348.el8.0.2.x86_64' prettyName='Rocky Linux 8.5 (Green Obsidian)'"

On the future vSphere 8.0 with vHW 20 enabled that same Rocky Linux 8.5 ("other4xlinux-64") VM with open-vm-tools 12.0.0 will show:

![image](https://user-images.githubusercontent.com/21000644/154180096-9f2a4043-e078-475e-a51f-701deb3ce1d0.png)

- or -

![image](https://user-images.githubusercontent.com/21000644/154179752-8794520d-fbe6-4a29-8532-4003928d7ee8.png)

**Comment by johnwvmw** [comment]
Are there any questions or further concerns regarding this topic?

Thanks.

**Comment by johnwvmw** [comment]
Closing this issue.   Please feel free to re-open or file a new issue if there are any questions.

Thanks
