### ISSUE TITLE
IP address changes take a long time to show up in vSphere

### ISSUE THREAD

**Issue by nre-ableton** [vmware/open-vm-tools#577]
### Describe the bug

We are deploying some Ubuntu 20.04 guests in vSphere (version 7.0.3.00300) with static IP addresses, which occasionally need to be changed. We manage this with Ansible playbooks, which alter the netplan YAML configuration file and then run `netplan generate` followed by `netplan apply`. The problem is, vSphere takes about 1-2 minutes to pick up the new IP address from the guest.

This is problematic because sometimes we have other playbooks that run directly after changing the IP address, and these playbooks use the [`vmware_guest_info` module](https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_info_module.html) to find the guest's IP address from the vSphere API, which is incorrect. This results in the playbooks connecting to the wrong guest, which can cause all sorts of problems.

As far as I can tell, this is caused by the `vmtoolsd` process not reporting the IP change to vSphere in a timely manner. I'm quite sure that this behavior is not the fault of Ansible or related tooling, because if I login to the vSphere client I can see that it also has the old IP address for about 1-2 minutes after making the change.

### Reproduction steps

```bash
1. Deploy Ubuntu 20.04 guest with a static IP address
2. Change the static IP address in the netplan config file
3. Run `netplan generate`
4. Run `netplan apply`
```

### Expected behavior

vSphere reports the correct IP address within a timely manner. Ideally, "timely" would be <1 second, but a few seconds delay is acceptable as well.

**Comment by lemke1458** [comment]
By default vmtoolsd looks at the guest network configuration every 30 seconds, so that's the longest delay you should see (note that there can still be delay getting it all the way up the management stack).  https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/tools.conf#L214

You could change this interval, but I don't recommend it since it puts extra strain on the guest to be constantly checking for a network change when they are rare.

Since you're actively modifying the guest, there's a vmware-toolbox-cmd that should help.

# vmware-toolbox-cmd info update network

will read and push the current guest network configuration into the vSphere stack.  Run this in the guest after the guest's network configuration has been changed.

**Comment by nre-ableton** [comment]
@lemke1458 Thanks for the tip, adding an Ansible task to run that command seems to be a good workaround for us. I was hoping that `open-vm-tools` would be able to listen to some sort of network status change event and then update the network accordingly rather than just polling. At any rate, as mentioned, the command is a good solution for us. Thanks for your help!

**Comment by lemke1458** [comment]
Glad it helped.

I experimented a while back with watching for network changes, but I found so many occurred at boot time that it ended up causing more problems, and we'd end up republishing partial data over & over.  IIRC there were a dozen changes just trying to set up 2 NICs in my test env.
