### ISSUE TITLE
Random clipboard disconnects with openSUSE Tumbleweed

### ISSUE THREAD

**Issue by ajgringo619** [vmware/open-vm-tools#603]
### Describe the bug

Not sure how to describe this, other than the copy/paste functionality of **open-vm-tools** will just disappear at random.

### Reproduction steps

```bash
1. Build new openSUSE Tumbleweed system
2. Enable copy/paste from host
3. Start copying commands to finish my install

Sometimes it will work, sometimes it won't. Sometimes clearing the guest's clipboard will help, sometimes it won't.
...
```

### Expected behavior

Copy/paste should always function. As a comparison, this is working flawlessly on **openSUSE LEAP 15.4**. The versions of **open-vm-tools** used are:
openSUSE Tumbleweed: 12.0.0-1.3
openSUSE LEAP 15.4: 12.0.0-150300.16.1

### Additional context

Both of these systems were built today and updated.

**Comment by PaTHml** [comment]
@ajgringo619 
Hi ajgringo619,

Filed an internal bug for the issue, we'll need more details and logs for the issue.

Version of VMware Workstation (or Fusion, or ESXi) being used.
Version of the Host (for workstation and fusion)
Linux desktop information: is it gnome with x11, with waylan; something else entirely (and versions).

In the case of Copy and Paste and Drag and Drop issues we require host and guest logs; we might also need your help in inspecting the guest os further.

The status of vmusr when the issue happened (pgrep -lf vmusr); was it running or not?

On the open-vm-tools, you would need to enable logs in tools.conf:

[logging]
log = true

# Enable tools service logging to a file.
vmtoolsd.level = debug
vmtoolsd.handler = file
vmtoolsd.data = /tmp/vmtoolsd.${USER}.log

# Enable 'dndcp' service logging to a file.
dndcp.level = debug
dndcp.handler = file
dndcp.data = /tmp/dndcp.log

# Enable new "vmusr" service logging to a file.
vmusr.level = debug
vmusr.handler = file
vmusr.data = tmp/vmusr.${USER}.log

# Enable "hgfsServer" request handling logging to the appropriate service file.
hgfsServer.level = debug
 
# Enable  "hgfs" manager and transport logging to the appropriate service file.
hgfsd.level = debug

As a start.

The ${USER} in the file names is not really needed if you have single user on the Guest OS. 
vmsvc usually has "root", while vmusr has the desktop login user.

Thanks

**Comment by PaTHml** [comment]
Looks like using '#' gets interpreted at a header line ... oh well.

**Comment by ajgringo619** [comment]
OK, I've made the requested changes. I'll keep this VM up for today and send the logs. For the host/guest info:
```
VMware Workstation 16.2.3 build-19376536
EndeavourOS, kernel 5.18.11-zen1-1-zen
XFCE 4.16 w/X11
```
When I first started the VM today, the `vmusr` process was running, both when the copy/paste worked and when it didn't.

**Comment by ajgringo619** [comment]
Figures that I can't make it fail anymore with the logging enabled. I've got the KDE clipboard open, along with the vmusr logs; every time I copy/cut/highlight anything on the host, the clipboard updates almost immediately.

**Comment by PaTHml** [comment]
Thanks,
Would be interesting to also get the vmsvc-*.log from the Guest. and the related vmware.log from the folder where the VM was deployed by VMware Workstation (my need the vmware.#.log or vmware-#.log as time passes).

**Comment by ajgringo619** [comment]
OK, will do. I'll have more time this evening.

**Comment by ajgringo619** [comment]
OK, I ran the guest for about 15 minutes, copy/pasting in both directions. Here are the (2) files:

[vmware.log](https://clbin.com/stF22)
[vmware-vmsvc-root.log](https://clbin.com/7h7Jv)

And of course, it's not failing anymore.

**Comment by polarathene** [comment]
I am not affected by this, but it may help to clarify the following:

- You are running an ArchLinux based host EndeavourOS with XFCE? And openSUSE TW/Leap guests with KDE?
- You state that clipboard sync initially always works but at some point during run-time it fails. Is that failure specific to the guest or if there is multiple guests running, can you confirm clipboard sync between the host or another guest is still working or are all guests and hosts impacted at the same time?
- You mention the failure is intermittent, how long does it usually take before the functionality is working again?
- Are you copying files at all? On my Manjaro host, copying a file with just ctrl+c in the file browser, and then moving the mouse into a guest implicitly transfers the file to the guest without any action on my behalf (this does not occur on a Fedora host however IIRC). This can be problematic with larger files taking time to copy over into the guests storage (_`~/.cache/vmware/drag_and_drop`, note this doesn't get automatically cleaned up to my knowledge_). It can be a blocking operation during the transfer, but I've also experienced a bug where smaller files would not show progress and just repeatedly duplicate copies into guest cache until the host updates the clipboard with text.
- Is the guest otherwise performing fine? If it becomes stuttery/laggy, you can inspect host memory with `free` to see how much is actually available, often VMware seems to fill up the buffer cache and by default may result in the host running `kcompact0` regularly until cleared. This could potentially be affecting your guest.
- If the delay between a clipboard sync failure becoming functional again is reasonable, perhaps you can verify if the sync eventually occurs with a large delay, rather than requiring clipboard update on the host or guest (_and the mouse crossing between the host DE and VM window boundary which AFAIK is required to trigger the sync_).
- Confirmation that both host and guest are X11. Gnome Wayland guests can handle clipboard sync, KDE Wayland cannot.
- Either host or guest running an OOM service like `systemd-oomd`, `nohang`, or similar that may kill a process related to the functionality, even when memory usage does not appear to be an issue (_Ubuntu 22.04 recently encountered this with `systemd-oomd` killing processes too eagerly_). Presumably your system isn't under memory pressure.

---

KDE switched to systemd startup by default with Plasma 5.25 (_a recent update, which may affect you if you've not had issues for some time prior_). Not all distros are starting the vmware services properly (_although this affects the guest straight away_).

Prior to that release, and for all other DE/distros AFAIK, a similar issue has been noticed with the service starting only sometimes (_again this would affect the guest from boot, and not work again until booted again or starting the service in the guest explicitly yourself_).

---

I've also noticed sometimes that the host needed a reboot because something went wrong there. Then guests behaved correctly.

**Comment by ajgringo619** [comment]
Both LEAP and TW VMs are running KDE w/X11. I never use copy/paste between guests, so that's irrelevant to me. I also never use drag/drop for files; got ssh/scp and shared folders for that. The failures usually happen at startup, but this can vary depending on how many copy/pastes I'm trying to make.

I'll check in the morning what the KDE version differences are from LEAP to TW. Thanks for the detailed reply.

**Comment by polarathene** [comment]
> I never use copy/paste between guests, so that's irrelevant to me.

It's relevant in narrowing the bug down. Doesn't have to be between guests, just verify that you can copy/paste from host to another guest when that doesn't work for the primary guest you're using.

> I also never use drag/drop for files; got ssh/scp and shared folders for that.

You misunderstood. You can ctrl+c a file on the host and it can be stored in the clipboard, switching to the guest can trigger an implicit transfer to the vmware cache directory, even if you never intend to paste the file in the guest.

Drag/drop is different feature, but the storage used is the same location.

---

> The failures usually happen at startup, but this can vary depending on how many copy/pastes I'm trying to make.

If they only happened at startup and never restored until restarting the guest, then this is a much better situation. One you can better resolve by ensuring you don't assign all CPU from host to the guest (or the opposite, more than 1 CPU to not bottleneck it).

openSUSE TW KDE at least should have the improved startup for `open-vm-tools` XDG autostart, I'm not sure if Leap got it but I assume so. Those work well with with the systemd startup for KDE Plasma 5.25 in my experience, other distros have to adopt the same approach otherwise the systemd startup in KDE now fails to start the service in time (5 second timeout).

**Comment by ajgringo619** [comment]
I've been using 8 of my 16 cores on my VMs now for years, so that's not an issue here. So far, I only have the (2) KDE VMs - LEAP and TW - and only TW is having the problems. In my research of this - and many other minor bugs - that KDE is just not as stable for me as the others I've tried (XFCE, Cinnamon, Gnome to name a few).

I will build an openSUSE TW XFCE VM and see how it works; this will at least eliminate `open-vm-tools` as the culprit.

**Comment by polarathene** [comment]
> and only TW is having the problems.

Is Leap running Plasma 5.25? I only tested TW KDE recently.

> KDE is just not as stable for me as the others I've tried (XFCE, Cinnamon, Gnome to name a few).

If Leap is not on Plasma 5.25, this is due to the recent change for how KDE startup now uses systemd units.

TW KDE was actually the only distro I tested that fixed it correctly, so it's a bit weird that it's not working for you.

> this will at least eliminate `open-vm-tools` as the culprit.

Partially. If it is only affecting KDE, it's not specifically KDE that is at fault, it's that the packaged `open-vm-tools` XDG autostart service isn't as compatible with systemd units IIRC.

**Comment by ajgringo619** [comment]
Yeah, from everything you've said, it sounds like I should be having these issues with LEAP, not TW.

**Comment by ajgringo619** [comment]
After taking a closer look, it looks like the problems are being caused by a flaky autostart of the **VMware User Agent**. Unfortunately, the errors are not consistent and don't say much. Here's an example:
```
Jul 23 09:35:51 opensuse-tw systemd[1464]: Starting VMware User Agent...
Jul 23 09:35:52 opensuse-tw vmtoolsd[1701]: gtk_disable_setlocale() must be called before gtk_init()
Jul 23 09:35:57 opensuse-tw systemd[1464]: app-vmware\x2duser\x2dautostart@autostart.service: start operation timed out. Terminating.
Jul 23 09:35:57 opensuse-tw systemd[1464]: app-vmware\x2duser\x2dautostart@autostart.service: Failed with result 'timeout'.
Jul 23 09:35:57 opensuse-tw systemd[1464]: Failed to start VMware User Agent.
```
On some days, it would actually start OK, then produce the aforementioned errors. Usually, though, this is happening at login.

**Comment by polarathene** [comment]
> After taking a closer look, it looks like the problems are being caused by a flaky autostart of the **VMware User Agent**.

This is one of the things I was talking about and [is tracked here](https://github.com/vmware/open-vm-tools/issues/568#issuecomment-1178736806).

Perhaps you can confirm what I found with TW, as it never failed with that distro due to their setup in my testing. Ensure you've got the [systemd startup for KDE enabled](https://wiki.archlinux.org/title/KDE#systemd_startup):

```bash
kwriteconfig5 --file startkderc --group General --key systemdBoot true
```

Then look at my "service status logs" snippets that show failures/success for the service.

In your case a failure should be listed with `systemctl --user --all status` and scroll down until you see the log lines you shared about the vmware autostart service failing. You should see more information about why it failed, and it's probably due to timeout.

The service needs to complete within 5 seconds, which from my findings, the TW KDE workaround script was resolving 100% of the time.

**Comment by ajgringo619** [comment]
I think we can close this for now; seems like a dupe of the other issues you've mentioned. After running the command above, the service started OK:
```
● app-vmware\x2duser\x2dautostart@autostart.service - VMware User Agent
     Loaded: loaded (/etc/xdg/autostart/vmware-user-autostart.desktop; generated)
     Active: active (running) since Tue 2022-07-26 10:28:40 PDT; 49s ago
       Docs: man:systemd-xdg-autostart-generator(8)
    Process: 1636 ExecStart=/usr/bin/vmware-user-autostart-wrapper (code=exited, status=0/SUCCESS)
   Main PID: 1636 (code=exited, status=0/SUCCESS)
      Tasks: 4 (limit: 9418)
     Memory: 39.1M
        CPU: 366ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/app-vmware\x2duser\x2dautostart@autostart.service
             └─1657 /usr/bin/vmtoolsd -n vmusr --blockFd 3

Jul 26 10:28:40 opensuse-tw systemd[1404]: Starting VMware User Agent...
Jul 26 10:28:40 opensuse-tw systemd[1404]: Started VMware User Agent.
Jul 26 10:28:41 opensuse-tw vmtoolsd[1657]: gtk_disable_setlocale() must be called before gtk_init()
```
Thank you so much for your help and insight!

**Comment by willzhang** [comment]
> > 仔细查看后，问题似乎是由 VMware 用户代理的不稳定自动启动引起的。
> 
> 这是我正在谈论的事情之一，并在此处进行跟踪。
> 
> 也许您可以确认我在 TW 中发现的情况，因为由于我的测试中的设置，该发行版从未失败。确保您已启用 KDE 的 systemd 启动：
> 
> ```shell
> kwriteconfig5 --file startkderc --group General --key systemdBoot true
> ```
> 
> 然后查看我的“服务状态日志”片段，其中显示服务的失败/成功。
> 
> 在您的情况下，故障应以 `systemctl --user --all status` 列出，并向下滚动，直到看到您共享的有关 vmware 自动启动服务失败的日志行。您应该看到有关失败原因的更多信息，这可能是由于超时造成的。
> 
> 该服务需要在 5 秒内完成，根据我的发现，TW KDE 解决方法脚本的解析率是 100%。

thanks
