### ISSUE TITLE
Is open-vm-tools subject to VMSA-2022-0024/CVE-2022-31676?

### ISSUE THREAD

**Issue by bellwood** [vmware/open-vm-tools#608]
### Describe the bug

Filing as a bug because the formal VMware website:

https://www.vmware.com/security/advisories/VMSA-2022-0024.html

...doesn't mention anything about open-vm-tools being affected.

Please clarify?

Thank you.

### Reproduction steps

```bash
1. Use open-vm-tools
2. Be notified about CVE in VMware-tools
3. See no clarification about open-vm-tools in the VMSA
```

### Expected behavior

VMware should indicate whether open-vm-tools is subject to the CVE/VMSA within their announcement(s)

**Comment by johnwvmw** [comment]
The VMSA should have specifically used the product name "open-vm-tools" instead of VMware Tools for Linux.   The revision was submitted but apparently missed.

The "just-released" open-vm-tools 12.1.0 announcement

   https://github.com/vmware/open-vm-tools/releases/tag/stable-12.1.0
   
 also mentions that VMSA link as well as a link to a set of patches that can be directly applied to earlier releases of open-vm-tools.   Follow that link to:
 
    https://github.com/vmware/open-vm-tools/blob/CVE-2022-31676.patch/README.md

**Comment by bellwood** [comment]
@johnwvmw thank you very much =)

**Comment by johnwvmw** [comment]
If there are no more questions on this issue, I will close it.

Please re-open if there are any addition questions.

Thanks.
