### ISSUE TITLE
Error installing on Debian 10.12

### ISSUE THREAD

**Issue by jamescoburn** [vmware/open-vm-tools#616]
### Describe the bug

When attempting to install on Debian 10.12, get error:
`configure.ac:133: error: possibly undefined macro: AC_MSG_WARN
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.`

Am I missing a package, etc.?  I ran apt update && apt upgrade first, then apt install automake and installed all indicated dependencies.

### Reproduction steps

1.  curl -L https://github.com/vmware/open-vm-tools/archive/master.tar.gz
2.  tar -xvzf master.tar.gz
3.  cd open-vm-tools-master/open-vm-tools
4.   autoreconf -i

### Expected behavior

Not sure what to expect, except not receiving an error.

**Comment by johnwvmw** [comment]
Confirmed that the source bundle link given is for the the open-vm-tools 12.1.0 release.

By "apt install automake and installed all indicated dependencies" I am assuming that you have installed/updated autoconf and libtools ?

Please try doing 
 **autoreconf -fi** 

The "-f" option will insure that the auto* and libtool related files are in sync with the version of those tools on your system.

I will update the README.md file with the addition of the "-f" option.

Please let us know if this does not resolve your problem or if you encounter further problems.

**Comment by jamescoburn** [comment]
Thanks, john.  However, adding f to the autoreconf switch did not resolve the issue - I still get the same error about the AC_MSG_WARN.

When I installed automake, it also installed the following packages:
autoconf
autotools-dev
libsigsegv2
m4

**Comment by johnwvmw** [comment]
When you installed "automake", the other 4 packages that you listed are loaded.

What you have apparently missed are the suggestions provided at that time:

`The following additional packages will be installed:
  autoconf autotools-dev libsigsegv2 m4
Suggested packages:
  autoconf-archive gnu-standards autoconf-doc libtool gettext m4-doc
`

Note the mention of libtool.

The full error from the **autoreconf -i** command is 
`$ autoreconf -i 
configure.ac:133: error: possibly undefined macro: AC_MSG_WARN
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:380: error: possibly undefined macro: AC_PROG_LIBTOOL
autoreconf: /usr/bin/autoconf failed with exit status: 1`

Again an error because of the absence of "libtool"

Installing "libtool" will also install dependent package - binutils, gcc and other packages needed for compilation and linking of C and C++ source code.

After that you will need several other open-source packages in order to build open-vm-tools.

The URL https://packages.debian.org/source/buster/open-vm-tools provides a list of other packages related to open-vm-tools on Debian>

**Comment by johnwvmw** [comment]
@jamescoburn 
FYI:   Following the "apt update && apt upgrade that you did, the open-vm-tools packages on your system should have been updated to version (2:10.3.10-1+deb10u3) [security].   This security update contained the fix for the recent VMware Security Announcement ( VMSA-2022-0024.1 ) - CVE-2022-31676

**Comment by johnwvmw** [comment]
Here is the list of packages that VMware uses to build internal open-vm-tools packages for Debian 10.  It is based on the OVT package source used by Debian & Ubuntu.
`  apt-get update && \
  apt-get install -y \
     build-essential \
     vim \
     autotools-dev \
     debhelper \
     dh-autoreconf \
     doxygen \
     libcunit1-dev \
     libfuse-dev \
     libgtk-3-dev \
     libgtkmm-3.0-dev \
     libicu-dev \
     libnotify-dev \
     libpam0g-dev \
     libprocps-dev \
     libx11-dev \
     libxinerama-dev \
     libxss-dev \
     libxtst-dev \
     libmspack-dev \
     libssl-dev \
     libxmlsec1-dev \
     libudev-dev \
     libprocps-dev \
     libdrm-dev \
     liblzma-dev \
     libgdk-pixbuf-xlib-2.0-dev \
     gawk \   <<== salt-minion plugin
     curl \
     libgrpc++1 \     <<==   containerInfo plugin
     libcurl4-openssl-dev \
     protobuf-compiler \
     libprotobuf-dev \
     protobuf-compiler-grpc \
     libgrpc++-dev \
     golang-github-containerd-containerd-dev \
     golang-github-gogo-protobuf-dev \
     && \
  apt-get clean
`

The "debhelper" and "dh-autoreconf" bring in the automake, autoconf and libtools packages.

The AC_MSG_WARN is coming when processing the configuration for the graphical OSS packages and it is because the "pkg-config" package is not installed.  The "libgtk-3-dev" depends on the "pkg-config" package.

Thanks to @jonathanvmw for the google search https://ae1020.github.io/undefined-macro-pkg-config/ and pointing out the last comment in #[478](https://github.com/vmware/open-vm-tools/issues/478).

**Comment by jozsef-85** [comment]
I have the same problem,
Who could solve it?

**Comment by johnwvmw** [comment]
Which of the issues listed above are the "same problem" that you are experiencing?

What Linux release and version are you using to do the open-vm-tools build?

What version of open-vm-tools are you trying to build?

Have you followed all the steps mentioned above including installing the required packages in order to do the autoconf, ./configure and make?   Did you also install "pkg-config" as mentioned above?
