### ISSUE TITLE
Unable to install open-vm-tools in RHEL 8.6 Getting error checking for libmspack >= 0.0.20040308alpha (via pkg-config)... no configure: error: mspack >= 0.0.20040308alpha is required.

### ISSUE THREAD

**Issue by vibhava-collab** [vmware/open-vm-tools#622]
### Describe the bug

Unable to install open-vm-tools in RHEL 8.6 Getting error checking for libmspack >= 0.0.20040308alpha (via pkg-config)... no configure: error: mspack >= 0.0.20040308alpha is required.

### Reproduction steps

Unable to install open-vm-tools in RHEL 8.6 Getting error checking for libmspack >= 0.0.20040308alpha (via pkg-config)... no configure: error: mspack >= 0.0.20040308alpha is required.

### Expected behavior

vmware-toolbox-cmd -v
12.1.0.37487 (build-20219665)

**Comment by cywebit** [comment]
I have same issue trying to install open-vmware-tools 12.10 when run ./configure on Jammy Jelly 22.04
libmspack>=0.0.20040308alpha is required.

Any thoughts?

**Comment by jonathanvmw** [comment]
@cywebit

This error is usually a sign that your system doesn't have the libmspack-dev package installed.  That package is needed for building open-vm-tools from source.

**Comment by johnwvmw** [comment]
It certainly sounds as if each are trying to build open-vm-tools from a source bundle.  

If the reason is to address the security issue announced in [VMSA-2022-0024](https://www.vmware.com/security/advisories/VMSA-2022-0024.html), please know that your Linux vendors have released a new package containing the security fix.  Simply"update" your package repository information and the upgrade the open-vm-tools packages on you Linux release.

   RHEL - yum update;  yum upgrade open-vm-tools [ open-vm-tools-desktop ]
   Ubuntu - apt update;  apt upgrade open-vm-tools [ open-vm-tools-desktop ]

**Comment by johnwvmw** [comment]
If you want to build from the open-vm-tools source bundle, know that you will need a number of development packages in order to compile the open-vm-tools daemons, plugins and commands.   See the list of packages needed for Debian and Ubuntu builds mentioned in #616

**Comment by johnwvmw** [comment]
Since there has been no further activity on this issue, closing this issue.

Please reopen if needed.

**Comment by HarimbolaSantatra** [comment]
I encounter this issue again on Ubuntu 22. For those in need, the solution was to install [`libmspack` and `libmspack-dev`](https://launchpad.net/ubuntu/+source/libmspack) as @jonathanvmw said.
