### ISSUE TITLE
vmware-checkvm does not detect virtualization for XCP-NG OS

### ISSUE THREAD

**Issue by dredknight** [vmware/open-vm-tools#632]
### Describe the bug

When vmware-checkvm is run inside a VMWare Workstation 16 VM running [XCP-NG 8.2](https://xcp-ng.org) OS it cannot detect it is being virtualized.
```
[12:46 localhost ~]# vmware-checkvm 
Not running in a virtual machine.
```

### Reproduction steps

1. Install a VM from latest [XCP-NG](https://xcp-ng.org/)
2. Once booted install open VM tools from Centos 7 repository
```
yum install open-vm-tools --enablerepo=base
```
4. Run vmware-checkvm 

### Expected behavior

vmware-checkvm should report that vm is being virtualized.

### Additional context

XCP-NG 8.2 is based on Centos 7.
```
[12:50 localhost ~]# uname -a
Linux localhost 4.19.0+1 #1 SMP Mon Dec 19 15:53:02 CET 2022 x86_64 x86_64 x86_64 GNU/Linux
```
_No response_

**Comment by PaTHml** [comment]
Given the output message from vmware-checkvm, it looks like the I/O port for the guest<->host rpc is not ... available or detected. I don't see XCP-NG on the compatibility list, did it work on earlier versions using the centos 7 open-vm-tools package? 

What was used as the Guest OS family and Guest OS when creating the virtual machine was it:
Linux+other-linux-64 or Linux+centos7, or something else? 

Thank you for reporting the problem; an internal issue was opened.

**Comment by PaTHml** [comment]
vmware-checkvm return 0 only when it detects it is running in a VMware virtual environment. The main determination point for this is looking at the "Hypervisor vendor" (hypervisor_id) in cpuid. In the case of the XCP-NG VM I deployed to reproduce this I see lscpu repoting this as "Xen" when "VMware" is expected.

Something in the XCP-NG OS is providing this value rather than getting it from the underlying hypervisor (Workstation or ESXi). 

As such, vmware-checkvm is performing as expected and reporting the VM is not a VMware VM.

You will want to take this up with the XCP-NG maintainers regarding how the cpuid calls/access and the hypervisor_id value is handled at the OS level.

**Comment by PaTHml** [comment]
To confirm this, you would need to get or rebuild the Debug version of vmware-checkvm; it has relevant logging for the detection decision points regarding the cpuid values.

**Comment by PaTHml** [comment]
Could also be as simple as XCP-NG need a custom configuration to enable running as a VM to fix the issue. Also something to ask from XCP-NG support.

**Comment by dredknight** [comment]
@PaTHml upgraded Workstation from 16 to 17 and that fixed the thing.
I assume it is related to backend because the vm is the same.
now vmware-check reports VMware!

The only workaround that should be done in order to run vmtoolsd and vgauthd is to comment
```
ConditionVirtualization=vmware
```
 in /etc/systemd/system/multi-user.target.wants/vmtoolsd.service
and
/etc/systemd/system/vmtoolsd.service.requires/vgauthd.service

If all is good you can close the issue!
Thank you.

**Comment by PaTHml** [comment]
Strange, what's the output for:
`lscpu | grep -i hyper`

after the upgrade of VMware Workstation 16 to 17 ?

**Comment by dredknight** [comment]
```
Hypervisor vendor:     VMware
Flags:                 fpu de tsc msr pae mce cx8 apic sep mca cmov pat clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase bmi1 avx2 bmi2 erms rdseed adx clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 gfni vaes vpclmulqdq rdpid arch_capabilities
```

**Comment by PaTHml** [comment]
Thank you.

**Comment by lars18th** [comment]
Hi,

Please, I need help with this:

I've installed XCP-NG inside Vmware Workstation 17 with nested virtualization enabled.
However `lscpu | grep -i hyper` returns `Hypervisor vendor: Xen`.
So, ...

- which version of `open-vm-tools` are you using? My is `yum list installed | grep vm-tools` --> `open-vm-tools.x86_64            11.0.5-3.el7  @base`
- I do the edition of the service files to comment out `#ConditionVirtualization=vmware`. But this doesn't fix anything.

Any idea?
Thank you.

**Comment by lars18th** [comment]
Hi @PaTHml ,

Sorry, but the question has been addressed to @dredknight because hi has solved the problem.

Fortunately, however, I've found the problem: in my case the error is because the inclusion of `hypervisor.cpuid.v0 = "FALSE"` inside the vmx file. That's the cause for not working it.

So, as a summary:
- You can run XCP-NG v8.2 inside VMware Workstation 17 with nested virtualization enabled, and with open-vm-tools running in XCP-NG to control the shutdown.
- Tips to install XCP-NG as a virtual machine: Select as much of RAM as you can, use 1 core per socket with multiple CPUs, use VMXNET3 virtual nics, use NVME as virtual drive type, add to the advanced configuration (VMX file): `ethernet0.noPromisc = "FALSE"` and `hypervisor.cpuid.v0 = "FALSE"`. And select/check in the Processor category: "Virtualize Intel VT-x/EPT or AMD-V/RVI". Then do a regular install.
- Tips for running XCP-NG as a virtual machine: Remove the advanced configuration `hypervisor.cpuid.v0 = "FALSE"` (useful only when installing). Reboot and Install the open-vm-tools package: `yum install open-vm-tools --enablerepo=base`. Check it with commands `vmware-checkvm`, `vmware-toolbox-cmd -v` and `systemctl status vmtoolsd`. Finally try to call to Guest Shutdown from the VMware Workstation UI and see that running VMs in XCP-NG will close previous to the shutdown.

And another tip for AMD users using Windows 10: If you have installed WSL2, then to start XCP-NG with nested virtualization with VMware Wokstation 17 you *only* need to disable the hypervisor support at boot: `bcdedit /set hypervisorlaunchtype off`. You can restore it at any time with: `bcdedit /set hypervisorlaunchtype auto`. Therefore if you *duplicate* your BCD boot entry to another one with hypervisor disabled, then you can boot selecting: regular boot (with WSL2 enabled) by default, or hyper-v off for running nested virtualization (aka XCP-NG as virtual machine). And futhermore, if you hide the boot menu, then you'll boot everytime with hyper-v enabled (auto mode). And if you select in Windows to reboot (pressing SHIFT key while selecting to reboot) then you will see the menu to select the boot OS. Then on it select to boot with the _alternative_ mode without hyper-v (ready for XCP-NG). I hope this help users using Ryzen processors and Windows 10 like me.

Regards.
