### ISSUE TITLE
Kubuntu 22.04.2 System crashs when opening konsole

### ISSUE THREAD

**Issue by weignerg** [vmware/open-vm-tools#667]
### Describe the bug

Kubuntu 22.04.2 is crashing when trying to use it.

It crashes to a black screen after I log in and when I open konsole.

I can Alt+PrintScreen + REISIUB to reboot the system.

After the crash or when I boot the system to the login I can press
Ctrl+Alt+f2 to log into a terminal.

The following is seen in /var/log/syslog.
See picture for more of the log.

```
kernel: [ 79.000000] vmwgfx 0000:00:0f.0: [drm] *ERROR* Could not find buffer object to map
kernel: [ 79.000000] BUG: kernel NULL pointer dereference, address: 0000000000000010
```

![image](https://github.com/vmware/open-vm-tools/assets/29870826/3879e317-0389-4923-9f49-f1b1e262ea0c)

I am running on Windows 10.
Hyper-V is not installed.
Windows Subsystem for Linux is not installed.
Virtual Machine Platform is installed.

### Reproduction steps

1. Download and Install VMware Pro 17.0.1
2. https://www.vmware.com/products/workstation-pro/workstation-pro-evaluation.html
3. Download and install kubuntu in vmware pro 17 with all the defaults chosen.
4. https://cdimage.ubuntu.com/kubuntu/releases/22.04.2/release/kubuntu-22.04.2-desktop-amd64.iso
5. Boot into the VM and log in.
6. Open konsole.
7. System crashes.

### Expected behavior

It is expected that kubuntu should not crash.

**Comment by weignerg** [comment]
I am trying it on another machine but with vmware pro 17 on kubuntu 22.04 instead of windows 10.

**Comment by weignerg** [comment]
> I am trying it on another machine but with vmware pro 17 on kubuntu 22.04 instead of windows 10.

It does the same thing with vmware pro 17.0.2 on kubuntu 22.04.

**Comment by weignerg** [comment]
The kernel gpu driver vmwgfx is where the error is being logged from.

https://github.com/torvalds/linux/blob/9e87b63ed37e202c77aa17d4112da6ae0c7c097c/drivers/gpu/drm/vmwgfx/vmwgfx_ttm_glue.c#L55

I am not sure if this is in any way related to open-vm-tools.

I am not sure how to report the issue on the kernel.

Not able to see Issues section on the github page.

**Comment by weignerg** [comment]
I am attempting to upgrade from the latest LTS version to the latest NORMAL version of Kubuntu 23.04 to see if the next supported kernel has the issue fixed.

**Comment by weignerg** [comment]
Bug is fixed in newer version of kernel.
Update to 23.04 fixes the issue.

**Comment by lousybrit** [comment]
I will report the bug and send it to our graphics developers for analysis.
I will also mention that Kubuntu 22.04 has the issue but kubuntu 23.04  does not.
I will see if they can report any fixes or updates here.

Thanks for reporting.
Steve

**Comment by juergenhuber** [comment]
Hey @lousybrit:

I'm facing the same issue in 22.04 here. The situation breaks the system (reproducible in both of my VMs) by using GUI only applications as well. This happens after an unpredictable amount of time (~1 - 30 minutes uptime). After the error, the KDE login screen is shown. It can be confirmed, that the system is stable until kernel 5.19.0-41-generic and starts to break with kernel 5.19.0.42-generic.

When booting the system manually with kernel 5.19.0.41-generic, everything is fine again. I've tested with latest 22.04 kernel, which is in the public repos 5.19.0.43-generic, but also this version is affected by the bug. Thus, I'm not sure, if upgrading to 23.04 will fix the issue in all circumstances. It might also be, that the latest kernel was not delivered to this non-LTS version.

**Comment by squinky86** [comment]
This has been a problem for the -41, -43, and now the -45 kernel.

**Comment by lousybrit** [comment]
Sorry for the delay; been hectic over the last few weeks.

Here is the response from the graphics team:
It looks like the github issue already has a note saying that this has been fixed in later versions of the kernel. In particular any kernels which contain:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/gpu/drm/vmwgfx?id=1a6897921f52ceb2c8665ef826e405bd96385159
and
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/gpu/drm/vmwgfx?id=a950b989ea29ab3b38ea7f6e3d2540700a3c54e8

Both those commits have been marked as backports for any kernel 5.17 and up so we have to wait for them to migrate to distros specific kernels or for distros to pickup newer kernels but we don't have control over when that happens.

==============================================================================

So they claim that it is a waiting game for this to be picked up and distributed.
Thanks,
Steve
