### ISSUE TITLE
What is the define USERWORLD for?

### ISSUE THREAD

**Issue by tomholtzen** [vmware/open-vm-tools#69]
What does the USERWORLD define used for. I'd like to use it so that in the rpcChannel.c just the backdoor channel is used. 
# if (defined(**linux**) && !defined(USERWORLD)) || defined(_WIN32)

   chan = (gUseBackdoorOnly || gVSocketFailed) ?
          BackdoorChannel_New() : VSockChannel_New();
# else

   chan = BackdoorChannel_New();
# endif

Would this be an appropriate thing to do? 
Also were are vmkuserstatus.h and vmkuseruptime.h?
# ifdef USERWORLD
# include <vm_basic_types.h>
# include <vmkuserstatus.h>
# include <vmkuseruptime.h>
# endif

Thanks,
Tom

**Comment by ravindravmw** [comment]
USERWORLD define is used by other VMware products that use this code. This is not relevant when one is building open-vm-tools. I'm sure you would get lots of compilation errors when you use that define. You should not need to use that define for building open-vm-tools.

I'm curious why do you want to use backdoor channel only? What is the problem you are facing with the existing behavior?

Though it is not recommended to do so, we have an API RpcChannel_SetBackdoorOnly() to force RpcChannel to use backdoor only, see https://github.com/vmware/open-vm-tools/blob/master/open-vm-tools/lib/rpcChannel/rpcChannel.c#L653.

**Comment by tomholtzen** [comment]
Thanks Ravindra.

In our product we were using an older version of open-vm-tools and it does not have this vsocket code. We're upgrading to a newer kernel and open-vm-tools and have built with --without-kernel-modules. We are not loading the vsock or vmci kernel modules. We get the following warning when running which don't exist with the older code.

[Jan 15 01:20:44.336] [    info] [vmsvc] SOCKET creating new socket, connecting to 0:975
[Jan 15 01:20:44.336] [ warning] [vmsvc] SOCKET failed to create socket, error 97: Address family not supported by protocol
[Jan 15 01:20:44.336] [   debug] [vmsvc] RpcIn: Error in creating vsocket connection: Connection error
[Jan 15 01:20:44.336] [   debug] [vmsvc] VSockChan: Creating privileged vsocket ...
[Jan 15 01:20:44.337] [ warning] [vmsvc] SimpleSock: Couldn't get VMCI socket family info.
[Jan 15 01:20:44.338] [ warning] [vmsvc] VSockChan: Failed to create vsocket channel, err=1
[Jan 15 01:20:44.338] [ warning] [vmsvc] RpcChannel: Fallback to backdoor …

It seems like we need to build with the vsock and vmci kernel models and load them to eliminate these warnings. Is that correct?
Are these vsocket calls the preferred way now? What additional advantage does it give us over the older code?
Would we be missing any functionality by not loading the vsock or vmci kernel modules and using the backdoor? 
Is there a way to remove the warnings (maybe by using RpcChannel_SetBackdoorOnly()), or would I just have to go into my local source to remove them.

Thanks,
Tom

**Comment by ravindravmw** [comment]
> It seems like we need to build with the vsock and vmci kernel models and load them to eliminate these warnings. Is that correct?

Yes, you should build your kernel with the upstreamed VMware drivers e.g. vmmemctl, vmxnet3, vmci, vsock etc. We don't recommend building drivers from open-vm-tools, instead we recommend building the Linux kernel with the upstreamed drivers. Once you have vmci and vsock drivers loaded in the kernel all warnings will go away if your ESXi host is v6.0 or later. Older hosts don't support VMCI channel for open-vm-tools, so you would still see some of the warnings (mainly fallback related) with older hosts.

> Are these vsocket calls the preferred way now? What additional advantage does it give us over the older code?

Yes, this is the preferred way because it is more secure.

> Would we be missing any functionality by not loading the vsock or vmci kernel modules and using the backdoor? 

No.

> Is there a way to remove the warnings (maybe by using RpcChannel_SetBackdoorOnly()), or would I just have to go into my local source to remove them.

Calling RpcChannel_SetBackdoorOnly() would remove these, but that would require modifying open-vm-tools code to add this call. I wouldn't advise this because of following reasons:
1. You would need to understand licensing implications of doing this. I'm not licensing expert to offer any advice on this.
2. Your code would be different from VMware provided code. Support and maintenance will get little harder for you.

IMO, the simplest solution would be to add the missing drivers to Linux kernel.

**Comment by stanguturi** [comment]
Please check the previous comment from Ravindra for all the answers. I don't see any pending questions. Closing this issue.
