### ISSUE TITLE
vmtoolsd info-get guestinfo.userdata Permission denied when called twice

### ISSUE THREAD

**Issue by playerla** [vmware/open-vm-tools#692]
### Describe the bug

Hi, 
I just find this behaviour - probably a bug
```
root@vm:~# vmtoolsd --cmd  'info-get guestinfo.userdata' ; vmtoolsd --cmd  'info-get guestinfo.userdata'
CiNjbG...=
Permission denied
```
It causes https://github.com/canonical/cloud-init/issues/4475

### Reproduction steps

1. Set userdata in vmx
2. Run the command `vmtoolsd --cmd  'info-get guestinfo.userdata' ; vmtoolsd --cmd  'info-get guestinfo.userdata'`

### Expected behavior

Can use binary vmtoolsd without being time dependant (I suppose vmtoolsd is a synchronous call)

### Additional context

VSphere 6.7 Debian 11 open-vm-tools 
open-vm-tools/oldstable-security,now 2:11.2.5-2+deb11u2 amd64  [installé]
Secure RPC enable (guest_rpc.rpci.auth.cmd.info-get = "TRUE")

**Comment by rprabhud** [comment]
Hi,

I tested this in debian 11 (debian-11.7.0-amd64-netinst.iso) VM in ESX 6.7 (build 8169922) with guest_rpc.rpci.auth.cmd.info-get set to TRUE but could not reproduce the issue:
open-vm-tools/oldoldstable-security,now 2:11.2.5-2+deb11u4 amd64 [installed,automatic]
root@lvn-dvm-10-163-1-186:~#
root@lvn-dvm-10-163-1-186:~# vmtoolsd --cmd  'info-get guestinfo.userdata' ; vmtoolsd --cmd  'info-get guestinfo.userdata'
No value found
No value found

As per the following o/p in issue description, first command was successful but second failed.
My suspect is failure is due to fallback to backdoor channel, but there are no logs to check and confirm.

Can you please share the details of repro steps to root cause it? And also the exact ESX version?

Thanks.
