### ISSUE TITLE
 open-vm-tools 12.3.5 make avaible for Ubuntu 20.04 LTS ( Focal Fossa ) 

### ISSUE THREAD

**Issue by Muy69** [vmware/open-vm-tools#709]
### Is your feature request related to a problem? Please describe.

On Ubuntu 20.04 Focal Fossa the latest Version 2:11:3.0-2ubuntu0~ubuntu20.04.07 is based on Version 11.3 vmware fools which is flagged by VMWARE as outdated and critical 

### Describe the solution you'd like

Port back the Jammy Jellyfish to Focal Fossa

https://launchpad.net/ubuntu/+source/open-vm-tools/2:12.1.5-3~ubuntu0.22.04.4

**Comment by johnwvmw** [comment]
True, open-vm-tools 11.3.0 as originally released has known security issues.    However, as CVE are fixed in later OVT releases and announced, Linux vendors are provided with a set of patches for earlier versions of open-vm-tools the address the security issue(s).

Check with the Ubuntu security announcements.  I believe that open-vm-tools 2:11:3.0-2ubuntu0~ubuntu20.04.07 contains all the open-vm-tools CVEs addressed since the original 11.3.0 was released.

**Comment by Muy69** [comment]
@johnwvmw I dont understand why the still current Ubuntu 20.04 LTS  , which is still under LTS Support until **2025**, should not get current VMWARE Tools any longer ( Security, Feature )  , what is the intention behind that decision or why is there a Jammy Release for a Current 12.x VMWARE Tools Release , in the Content of your Explanation then ? 

As you closed the Request right away ,   So it is  sufficient to use the CVe Bugfix from *2022* and skip the Development for the Ubuntu 20.04 in the Context of **Features** and just fix some CVEs as it is necessary ? 

Therefor 3rd Party Software will lable the 11.03 VMWARE Tools  as old  , as it is ! The Version number is unchanged . 
 ( VMWARE released that Version  it in  **2021** for Esxi 7  )

**Comment by Muy69** [comment]
Just so that you know how that looks in a 3rd Party Tool ( RuneCast ) 

Critical: ( Event ! ) 
VMware Security Advisory: VMSA-2023-0013 (VMware Tools update addresses Authentication Bypass vulnerability (CVE-2023-20867))

CISA KEV due date
2023-07-14

Updated
2023-06-1

vmtools Version : 11.03 Critical ( The Info come from VMWARE API )
