### ISSUE TITLE
VM time not sync with host after reboot if guest time is ahead of host

### ISSUE THREAD

**Issue by wangjj1989** [vmware/open-vm-tools#85]
Move guest time ahead host 2 hours, reboot VM. When VM is on, time is still not sync with host.
This issue is only reproduced for vmtools 10.0.
## vmtools 10.0

The vmtools I used is the lates(download from github) and compile by myself. Following are steps:

---

root@ubuntu:/home/wang# uname -a  
Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux  
root@ubuntu:/home/wang# vmware-toolbox-cmd -v  
10.0.5.52125 (build-3227872)  
root@ubuntu:/home/wang# vmware-toolbox-cmd timesync status  
Enabled  
root@ubuntu:/home/wang# ps aux | grep vmtoolsd  
root      1091  0.0  0.8 107172  8824 ?        S    20:03   0:00 /usr/bin/vmtoolsd  
root      1242  0.0  0.2  11748  2180 pts/0    S+   20:04   0:00 grep --color=auto vmtoolsd  
root@ubuntu:/home/wang# date  
Wed Apr 27 20:04:41 SGT 2016  
root@ubuntu:/home/wang# date -s "20160427 22:04:41"  
Wed Apr 27 22:04:41 SGT 2016  
root@ubuntu:/home/wang# date  
Wed Apr 27 22:04:42 SGT 2016  
root@ubuntu:/home/wang# reboot  
<------after reboot---------------->  
root@ubuntu:/home/wang# ps aux | grep vmtoolsd  
root      1094  0.1  0.8 107172  8936 ?        S    22:05   0:00 /usr/bin/vmtoolsd  
root      1242  0.0  0.2  11748  2084 pts/0    S+   22:06   0:00 grep --color=auto vmtoolsd  
root@ubuntu:/home/wang# date  
Wed Apr 27*\* 22:06:36*\* SGT 2016

---

We can see that after reboot, VM's time is not sync with host.
## vmtools 9.4

Use vmtools 9.4 to test. Vmtools is intalled by 'apt-get install' from ubuntu repository.

---

root@ubuntu:/home/wang# uname -a
Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu:/home/wang# vmware-toolbox-cmd -v
9.4.0.25793 (build-1280544)
root@ubuntu:/home/wang# vmware-toolbox-cmd  timesync status
Enabled
root@ubuntu:/home/wang# ps aux | grep vmtoolsd
root      1028  0.0  0.6  89908  6768 ?        S    19:43   0:00 /usr/bin/vmtoolsd
root      1296  0.0  0.2  11748  2164 pts/0    S+   20:09   0:00 grep --color=auto vmtoolsd
root@ubuntu:/home/wang# date
Wed Apr 27 20:09:59 SGT 2016
root@ubuntu:/home/wang# date -s "20160427 22:09:59"
Wed Apr 27 22:09:59 SGT 2016
root@ubuntu:/home/wang# date
Wed Apr 27 22:10:00 SGT 2016

<------------after reboot--------------------->
root@ubuntu:/home/wang# date
Wed Apr 27 20:12:08 SGT 2016
root@ubuntu:/home/wang# ps aux | grep vmtoolsd
root      1056  0.0  0.6  89908  6836 ?        S    20:10   0:00 /usr/bin/vmtoolsd
root      1255  0.0  0.2  11748  2128 pts/0    S+   20:12   0:00 grep --color=auto vmtoolsd

---

We can find after reboot, VM's time is sync with host.

**Comment by wangjj1989** [comment]
Esxi host version is 6.

**Comment by wangjj1989** [comment]
Anyone has similar issue?

**Comment by wangjj1989** [comment]
@vito @dyno @sigma @pacogomez @ @pacogomez

**Comment by pengzhencao** [comment]
If guest's time is behind host's time, it could be adjusted in one shot.
If guest's time ahead of host's time, it will be adjusted gradually, otherwise there may be problems with other applications on the guest.
refer:
Configure Time Synchronization Between Guest and Host Operating Systems
https://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.vsphere.vm_admin.doc%2FGUID-C0D8326A-B6E7-4E61-8470-6C173FDDF656.html&resultof=%22Configure%22%20%22configur%22%20%22Time%22%20%22time%22%20%22Synchronization%22%20%22synchron%22%20%22Between%22%20%22between%22%20%22Guest%22%20%22guest%22%20%22Host%22%20%22host%22%20%22Operating%22%20%22oper%22%20%22Systems%22%20%22system%22%20

**Comment by wangjj1989** [comment]
Thanks for your reply @pengzhencao !
I have read that post. As far as my understanding, when the guest reboots, guest's time should sync with host no matter it is behind or ahead of host's. 
I believe it is a bug if my understanding is right.

You can see my test cases above.
If using vmtools 9.4, there is no problem. But for vmtools 10.0, after reboot, guest's time still does't sync.

**Comment by ravindravmw** [comment]
It is a new change in 10.0.0 and later Tools. We no longer move the guest clock backwards because one shot time jump backwards leads to some services getting stuck for long especially network related utilities like dhclient (https://bugzilla.redhat.com/show_bug.cgi?id=916116), arping (http://kb.vmware.com/kb/2048572).

Could you please explain why have you set guest clock ahead of host and then expecting it to be corrected? It would help us greatly to understand the affected use case here?

Also, have you considered using NTP for your VM?

**Comment by wangjj1989** [comment]
We integrate ovt( we compile it by ourselves)  in our vapp and we need to test it work smoothly or not.
No special reason, it just a test case to verify vm tools works fine.
Definitely, we can use NTP but we still test it.

**Comment by ravindravmw** [comment]
Thanks. If it is just a test, I think you might want to consider changing the test to not expect guest clock to move backwards suddenly during power on when using open-vm-tools version >= 10.0.0.

**Comment by stanguturi** [comment]
> Thanks. If it is just a test, I think you might want to consider changing the test to not expect guest clock to move backwards suddenly during power on when using open-vm-tools version >= 10.0.0.

Please change the test case accordingly. As mentioned earlier in one of the comments, this is working as expected.
