### ISSUE TITLE
Version 9.10.0 in yum repository

### ISSUE THREAD

**Issue by pall-valmundsson** [vmware/open-vm-tools#9]
Will the http://packages.vmware.com/packages/rhel7/x86_64/ repo be updated with 9.10.0?

**Comment by oliverkurth** [comment]
No. That repository provided just open-vm-tools-deploypkg as an add-on for open-vm-tools provided by Linux distributions. This is no longer needed with 9.10 because deploypkg is now included in the source, therefore the distributions can build and provide it.

But if you are referring to OSPs (under http://packages.vmware.com/tools/esx/), the answer is also no. Starting with RHEL 7, SLE 12 and Ubuntu 14.04 we recommend to use open-vm-tools as provided by the distributions.

**Comment by pall-valmundsson** [comment]
Of course, my misunderstanding :) Thanks for a quick answer.
