### ISSUE TITLE
Run additional scripts until VM customization

### ISSUE THREAD

**Issue by bashlakov** [vmware/open-vm-tools#99]
Hi!

Not sure, is it properly place for this question, but I can't find any information about topic.
Is there any possibility to run own script after deploy VM from template without vCloud Director?
I would like to automatically re-generate host ssh keys and add hostname string to zabbix-agent config after deploy VM.

Thanks!

**Comment by aneverov4vmw** [comment]
Hi,

The recommended way to do this would be to use vSphere Guest Operations API via SDK. Some example of that approach is given in http://www.virtuallyghetto.com/2011/07/automating-new-integrated-vixguest.html

**Comment by ybhasin** [comment]
Official documentation on vSphere GuestOps API can be found here: https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/vim.vm.guest.ProcessManager.html

**Comment by bashlakov** [comment]
Hi, thanks for replies!
This solution is more approach for larger automatization and add need for some external management system for using this API. My goal is to simplify deployment new VM with no additional systems. May I send feature-request or maybe push-request for adding the possibility to include custom scripts to guest customization process? I think it would be enough just to add few lines of code to perl-script, which does the customization process to check config folders (e.g. /etc/vmware-tools/scripts/customization) and run contained scripts with provided by template deployment wizard options.
I think, this may be useful way to extend the ability of deploying VM templates in middle-size installation, where using vCD or custom solution via GuestOps API is overkill.

**Comment by aneverov4vmw** [comment]
Hi,

The concern is clear. However, from the design perspective, guest customization (GOSC) is not a Tools feature. Tools only provide the base transport and execution mechanism - deployPkg plug-in. The GOSC engine itself is part of the other products like vCD or vCenter. In this case, vCenter doesn't have post-customization script feature like in vCD. A way to address that would be to file a Service Request to add it there such that we can make it consistent with the other features/designs/plans.

**Comment by ravindravmw** [comment]
@bashlakov is this needed for Linux only or all guests? Also, do you need any configuration from VM customization? If the requirement can be achieved by merely running a custom script without needing any configuration from VM deployment, you may want to consider achieving this via Tools custom power scripts. Tools picks custom power scripts from /etc/vmware-tools/scripts/${powerop}-default.d/ where ${powerop} is 'poweron-vm" for power on and 'poweroff-vm' for power off. You could have your non-blocking script in the directory above. This script could start your other main script in the background. This way your scripts would not block Tools progress during power on. Your main script can wait for system changes/events it cares about. It can delete itself and other script once it is done. It can also leave enough trace to make the future execution of these scripts a no-op. The cleanup is important because Tools will run the script whenever the relevant power operation is invoked.

**Comment by bashlakov** [comment]
Hi,
@ravindravmw I've interested this feature mainly in *nix OS, but I think there would be right to have similar mechanism in all supported OS. Your solution has main disadvantage: is this case user scripts run on every startup and it need to manually control that it was or wasn't ran before and script has no guaranty that customization process has to be completed at execution time.
@aneverov4vmw AFAIU customization process handled by deployPkg and my feature-request relates to this plugin. Am I right understood that you suggest to make feature-request in this repo?

**Comment by ravindravmw** [comment]
@bashlakov yes, the approach I mentioned is just a workaround for your use case, not the ideal solution. So, you will have to deal with the unintended side effects of the workaround. It depends on how urgently you want this.

> script has no guaranty that customization process has to be completed at execution time.

Unfortunately, today there is no supported way for finding out when customization is complete. We have an existing feature request for this.

**Comment by aneverov4vmw** [comment]
@bashlakov customization process is barely invoked by the deployPkg plug-in. It is its only responsibility and we would like it to remain so, because there might be potential designs where this plug-in and Tools as a whole might not participate in the customization process. The post-customization scripts functionality purely belongs to the GOSC engine itself which is part of products like vCenter and vCD, not Tools.

So, the feature request should not be for this repo. It should be raised with VMware Support to be considered for vCenter and/or any other VMware product you use.

**Comment by xiaofengw-vmware** [comment]
Hi all,
The capability to launch an additional scripts is supported from vsphere 7.0, please refer to the vsphere 7.0 VM administration for details. The functionalities you mentioned such as SSH key/host name are fully supported. Please have a try. Thanks.
https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-9A5093A5-C54F-4502-941B-3F9C0F573A39.html

**Comment by xiaofengw-vmware** [comment]
@bashlakov , have you tried this new feature on vsphere 7.0? Could we close this ticket if it can meet your requirements? Thanks.

**Comment by xiaofengw-vmware** [comment]
@oliverkurth @ravindravmw 
Could you help to close this issue since this function is already supported from vSphere 7.0? Thanks.

**Comment by bashlakov** [comment]
@xiaofengw-vmware, unfortunately I don't use vSphere anymore, so I couldn't check this feature.

**Comment by stanguturi** [comment]
> @oliverkurth @ravindravmw
> Could you help to close this issue since this function is already supported from vSphere 7.0? Thanks.

Thanks @xiaofengw-vmware for the update. The initial request to run additional scripts was implemented as a feature in the latest ESXi release (starting from ESXi 7.0). Closing this issue.
